import {
  auditEventsResponseSchema,
  listAgentAuditEventsQuerySchema,
  listAgentsQuerySchema,
  listManagementAgentAccessGrantsQuerySchema,
  listManagementAgentAccessRequestsQuerySchema,
  managementAgentAccessGrantSchema,
  managementAgentAccessGrantsResponseSchema,
  managementAgentAccessRequestSchema,
  managementAgentAccessRequestsResponseSchema,
  managementAgentInstallationsResponseSchema,
  managementAgentResponseSchema,
  managementAgentsResponseSchema,
} from '@shared/api/agent-api'
import { paginationQuerySchema } from '@shared/api/pagination'
import {
  jsonBody,
  type ManagementRouteConfig,
  requestAgentCapabilitiesResponseSchema,
  requestAgentCapabilitiesSchema,
  z,
} from './helpers'

export const agentGovernanceRoutes: ManagementRouteConfig[] = [
  {
    method: 'post',
    path: '/agent/capability-requests',
    operationId: 'requestAgentCapabilities',
    summary: 'Request Realmroot resource capabilities',
    cli: { group: 'capability', name: 'request' },
    security: [{ agentAuth: [] }],
    request: { body: jsonBody(requestAgentCapabilitiesSchema) },
    response: requestAgentCapabilitiesResponseSchema,
  },
  {
    method: 'get',
    path: '/agents',
    operationId: 'listAgents',
    summary: 'List stable Agents',
    request: { query: listAgentsQuerySchema },
    response: managementAgentsResponseSchema,
  },
  {
    method: 'get',
    path: '/agents/{agentId}',
    operationId: 'getAgent',
    summary: 'Get a stable Agent',
    request: { params: z.object({ agentId: z.string() }) },
    response: managementAgentResponseSchema,
  },
  {
    method: 'get',
    path: '/agents/{agentId}/installations',
    operationId: 'listAgentInstallations',
    summary: 'List installations authorized for a stable Agent',
    request: { params: z.object({ agentId: z.string() }), query: paginationQuerySchema },
    response: managementAgentInstallationsResponseSchema,
    errors: { 400: 'The pagination query is invalid.', 404: 'The Agent was not found.' },
  },
  {
    method: 'get',
    path: '/agent-access-requests',
    operationId: 'listManagedAgentAccessRequests',
    summary: 'List Agent access requests',
    request: { query: listManagementAgentAccessRequestsQuerySchema },
    response: managementAgentAccessRequestsResponseSchema,
    errors: { 400: 'The collection query is invalid.' },
  },
  {
    method: 'get',
    path: '/agent-access-requests/{requestId}',
    operationId: 'getManagedAgentAccessRequest',
    summary: 'Get an Agent access request',
    request: { params: z.object({ requestId: z.string() }) },
    response: managementAgentAccessRequestSchema,
    errors: { 404: 'The Agent access request was not found.' },
  },
  {
    method: 'get',
    path: '/agent-access-grants',
    operationId: 'listManagedAgentAccessGrants',
    summary: 'List Agent access grants',
    request: { query: listManagementAgentAccessGrantsQuerySchema },
    response: managementAgentAccessGrantsResponseSchema,
    errors: { 400: 'The collection query is invalid.' },
  },
  {
    method: 'get',
    path: '/agent-access-grants/{grantId}',
    operationId: 'getManagedAgentAccessGrant',
    summary: 'Get an Agent access grant',
    request: { params: z.object({ grantId: z.string() }) },
    response: managementAgentAccessGrantSchema,
    errors: { 404: 'The Agent access grant was not found.' },
  },
  {
    method: 'delete',
    path: '/agents/{agentId}',
    operationId: 'retireAgent',
    summary: 'Permanently retire an Agent',
    request: { params: z.object({ agentId: z.string() }) },
    noBody: true,
  },
  {
    method: 'get',
    path: '/audit-events',
    operationId: 'listAgentAuditEvents',
    summary: 'List Agent audit events',
    request: { query: listAgentAuditEventsQuerySchema },
    response: auditEventsResponseSchema,
  },
]
