import {
  accessRequestSchema,
  agentAccessGrantSchema,
  agentAccessGrantsResponseSchema,
  auditEventsResponseSchema,
  decideAccessRequestSchema,
  dpopNonceErrorResponseSchema,
  listAgentAccessGrantsQuerySchema,
  listAgentAuditEventsQuerySchema,
  listAgentsQuerySchema,
  listManagementAgentAccessRequestsQuerySchema,
  managementAgentAccessRequestSchema,
  managementAgentAccessRequestsResponseSchema,
  managementAgentInstallationsResponseSchema,
  managementAgentResponseSchema,
  managementAgentsResponseSchema,
  targetCredentialProofSchema,
  targetTokenSchema,
} from '@shared/api/agent-api'
import { managementErrorResponseSchema } from '@shared/api/management'
import { paginationQuerySchema } from '@shared/api/pagination'
import { jsonBody, type ManagementRouteConfig, z } from './helpers'

export const agentGovernanceRoutes: ManagementRouteConfig[] = [
  {
    method: 'get',
    path: '/access/requests/{requestId}/decision',
    operationId: 'getAgentAuthorizationRequestDecision',
    summary: 'Get an Agent authorization request decision',
    request: { params: z.object({ requestId: z.string() }) },
    response: z.object({ accessRequestId: z.string(), status: z.string(), decidedAt: z.string().nullable() }),
  },
  {
    method: 'put',
    path: '/access/requests/{requestId}/decision',
    operationId: 'replaceAgentAuthorizationRequestDecision',
    summary: 'Create or replace an Agent authorization request decision',
    request: {
      params: z.object({ requestId: z.string() }),
      body: { content: { 'application/json': { schema: decideAccessRequestSchema } } },
    },
    response: z.object({ accessRequestId: z.string(), status: z.string(), decidedAt: z.string().nullable() }),
  },
  {
    method: 'get',
    path: '/agents',
    operationId: 'listAgents',
    summary: 'List stable Agents',
    request: { query: listAgentsQuerySchema },
    response: managementAgentsResponseSchema,
  },
  {
    method: 'get',
    path: '/agents/{agentId}',
    operationId: 'getAgent',
    summary: 'Get a stable Agent',
    request: { params: z.object({ agentId: z.string() }) },
    response: managementAgentResponseSchema,
  },
  {
    method: 'get',
    path: '/agents/{agentId}/installations',
    operationId: 'listAgentInstallations',
    summary: 'List installations authorized for a stable Agent',
    request: { params: z.object({ agentId: z.string() }), query: paginationQuerySchema },
    response: managementAgentInstallationsResponseSchema,
    errors: { 400: 'The pagination query is invalid.', 404: 'The Agent was not found.' },
  },
  {
    method: 'get',
    path: '/access/requests',
    operationId: 'listAgentAuthorizationRequests',
    summary: 'List Agent authorization requests',
    request: { query: listManagementAgentAccessRequestsQuerySchema },
    response: managementAgentAccessRequestsResponseSchema,
    errors: { 400: 'The collection query is invalid.' },
  },
  {
    method: 'get',
    path: '/access/requests/{requestId}',
    operationId: 'getManagedAgentAuthorizationRequest',
    summary: 'Get an Agent authorization request',
    security: [
      { agentAuth: ['access-requests:read'] },
      { oauth2: ['agents:read'] },
      { sessionCookie: ['agents:read'] },
    ],
    request: { params: z.object({ requestId: z.string() }) },
    response: z.union([managementAgentAccessRequestSchema, accessRequestSchema]),
    errors: { 404: 'The Agent access request was not found.' },
  },
  {
    method: 'get',
    path: '/agents/{agentId}/access-grants',
    operationId: 'listAgentAccessGrants',
    summary: 'List an Agent’s access grants',
    security: [{ oauth2: ['access-grants:read'] }, { sessionCookie: ['agents:read'] }],
    request: { params: z.object({ agentId: z.string() }), query: listAgentAccessGrantsQuerySchema },
    response: agentAccessGrantsResponseSchema,
    errors: { 400: 'The collection query is invalid.' },
  },
  {
    method: 'get',
    path: '/agents/{agentId}/access-grants/{grantId}',
    operationId: 'getAgentAccessGrant',
    summary: 'Get an Agent access grant',
    security: [{ oauth2: ['access-grants:read'] }, { sessionCookie: ['agents:read'] }],
    request: { params: z.object({ agentId: z.string(), grantId: z.string() }) },
    response: agentAccessGrantSchema,
    errors: { 404: 'The Agent access grant was not found.' },
  },
  {
    method: 'delete',
    path: '/agents/{agentId}/access-grants/{grantId}',
    operationId: 'deleteAgentAccessGrant',
    summary: 'Delete an Agent access grant',
    security: [{ sessionCookie: ['agents:write'] }],
    request: { params: z.object({ agentId: z.string(), grantId: z.string() }) },
    noBody: true,
    errors: { 404: 'The Agent access grant was not found.' },
  },
  {
    method: 'post',
    path: '/access/requests/{requestId}/credentials',
    operationId: 'createAgentAccessRequestCredential',
    summary: 'Create a temporary credential for an approved Agent access request',
    security: [{ agentAuth: ['access-requests:write'] }],
    request: {
      params: z.object({ requestId: z.string() }),
      body: jsonBody(targetCredentialProofSchema),
    },
    response: targetTokenSchema,
    status: 201,
    responseHeaders: {
      'DPoP-Nonce': {
        description: 'Opaque authorization-server nonce to include in the next credential DPoP proof.',
        schema: { type: 'string' },
      },
    },
    errors: {
      400: {
        description: 'The request is invalid or the authorization server requires a nonce in a fresh DPoP proof.',
        schema: z.union([managementErrorResponseSchema, dpopNonceErrorResponseSchema]),
        headers: {
          'DPoP-Nonce': {
            description: 'Opaque authorization-server nonce required in the retry proof.',
            schema: { type: 'string' },
          },
        },
      },
    },
  },
  {
    method: 'get',
    path: '/agents/{agentId}/activation',
    operationId: 'getAgentActivation',
    summary: 'Get an Agent activation',
    request: { params: z.object({ agentId: z.string() }) },
    response: z.object({ agentId: z.string(), active: z.boolean() }),
  },
  {
    method: 'put',
    path: '/agents/{agentId}/activation',
    operationId: 'replaceAgentActivation',
    summary: 'Create or replace an Agent activation',
    request: { params: z.object({ agentId: z.string() }) },
    noBody: true,
  },
  {
    method: 'delete',
    path: '/agents/{agentId}/activation',
    operationId: 'deleteAgentActivation',
    summary: 'Delete an Agent activation',
    request: { params: z.object({ agentId: z.string() }) },
    noBody: true,
  },
  {
    method: 'delete',
    path: '/agents/{agentId}',
    operationId: 'deleteAgent',
    summary: 'Delete an Agent',
    request: { params: z.object({ agentId: z.string() }) },
    noBody: true,
  },
  {
    method: 'get',
    path: '/realm/audit-events',
    operationId: 'listAgentAuditEvents',
    summary: 'List Agent audit events',
    request: { query: listAgentAuditEventsQuerySchema },
    response: auditEventsResponseSchema,
  },
]
