import {
  accessRequestSchema,
  agentInstallationRevocationSchema,
  agentRecoverySchema,
  auditEventsResponseSchema,
  decideAccessRequestSchema,
  listAgentAuditEventsQuerySchema,
  listAgentsQuerySchema,
  listManagementAgentAccessGrantsQuerySchema,
  listManagementAgentAccessRequestsQuerySchema,
  managementAgentAccessGrantSchema,
  managementAgentAccessGrantsResponseSchema,
  managementAgentAccessRequestSchema,
  managementAgentAccessRequestsResponseSchema,
  managementAgentInstallationsResponseSchema,
  managementAgentResponseSchema,
  managementAgentsResponseSchema,
  targetCredentialProofSchema,
  targetTokenSchema,
} from '@shared/api/agent-api'
import { paginationQuerySchema } from '@shared/api/pagination'
import { jsonBody, type ManagementRouteConfig, managementErrorResponseSchema, z } from './helpers'

export const agentGovernanceRoutes: ManagementRouteConfig[] = [
  {
    method: 'get',
    path: '/access/requests/{requestId}/decision',
    operationId: 'getAgentAuthorizationRequestDecision',
    summary: 'Get an Agent authorization request decision',
    request: { params: z.object({ requestId: z.string() }) },
    response: z.object({ accessRequestId: z.string(), status: z.string(), decidedAt: z.string().nullable() }),
  },
  {
    method: 'put',
    path: '/access/requests/{requestId}/decision',
    operationId: 'replaceAgentAuthorizationRequestDecision',
    summary: 'Create or replace an Agent authorization request decision',
    request: {
      params: z.object({ requestId: z.string() }),
      body: { content: { 'application/json': { schema: decideAccessRequestSchema } } },
    },
    response: z.object({ accessRequestId: z.string(), status: z.string(), decidedAt: z.string().nullable() }),
  },
  {
    method: 'get',
    path: '/agents',
    operationId: 'listAgents',
    summary: 'List stable Agents',
    request: { query: listAgentsQuerySchema },
    response: managementAgentsResponseSchema,
  },
  {
    method: 'get',
    path: '/agents/{agentId}',
    operationId: 'getAgent',
    summary: 'Get a stable Agent',
    request: { params: z.object({ agentId: z.string() }) },
    response: managementAgentResponseSchema,
    security: [{ dpop: ['agents:read'] }, { sessionCookie: ['agents:read'] }],
  },
  {
    method: 'get',
    path: '/agents/{agentId}/installations',
    operationId: 'listAgentInstallations',
    summary: 'List installations authorized for a stable Agent',
    request: { params: z.object({ agentId: z.string() }), query: paginationQuerySchema },
    response: managementAgentInstallationsResponseSchema,
    security: [{ dpop: ['agent:read'] }, { dpop: ['agents:read'] }, { sessionCookie: ['agents:read'] }],
    errors: { 400: 'The pagination query is invalid.', 404: 'The Agent was not found.' },
  },
  {
    method: 'get',
    path: '/agents/{agentId}/installations/{installationId}/revocation',
    operationId: 'getAgentInstallationRevocation',
    summary: 'Get an Agent installation revocation',
    request: { params: z.object({ agentId: z.string(), installationId: z.string() }) },
    response: agentInstallationRevocationSchema,
    security: [{ dpop: ['agent:read'] }, { dpop: ['agents:read'] }, { sessionCookie: ['agents:read'] }],
  },
  {
    method: 'put',
    path: '/agents/{agentId}/installations/{installationId}/revocation',
    operationId: 'replaceAgentInstallationRevocation',
    summary: 'Create or replace an Agent installation revocation',
    request: { params: z.object({ agentId: z.string(), installationId: z.string() }) },
    response: agentInstallationRevocationSchema,
    security: [{ dpop: ['agent:write'] }, { dpop: ['agents:write'] }, { sessionCookie: ['agents:write'] }],
  },
  {
    method: 'get',
    path: '/access/requests',
    operationId: 'listAgentAuthorizationRequests',
    summary: 'List Agent authorization requests',
    request: { query: listManagementAgentAccessRequestsQuerySchema },
    response: managementAgentAccessRequestsResponseSchema,
    errors: { 400: 'The collection query is invalid.' },
  },
  {
    method: 'get',
    path: '/access/requests/{requestId}',
    operationId: 'getManagedAgentAuthorizationRequest',
    summary: 'Get an Agent authorization request',
    request: { params: z.object({ requestId: z.string() }) },
    response: z.union([managementAgentAccessRequestSchema, accessRequestSchema]),
    errors: { 404: 'The Agent access request was not found.' },
  },
  {
    method: 'get',
    path: '/access/authorizations',
    operationId: 'listAgentAuthorizations',
    summary: 'List Agent authorizations',
    request: { query: listManagementAgentAccessGrantsQuerySchema },
    response: managementAgentAccessGrantsResponseSchema,
    errors: { 400: 'The collection query is invalid.' },
  },
  {
    method: 'get',
    path: '/access/authorizations/{authorizationId}',
    operationId: 'getAgentAuthorization',
    summary: 'Get an Agent authorization',
    request: { params: z.object({ authorizationId: z.string() }) },
    response: managementAgentAccessGrantSchema,
    errors: { 404: 'The Agent access grant was not found.' },
  },
  {
    method: 'get',
    path: '/access/authorizations/{authorizationId}/revocation',
    operationId: 'getAgentAuthorizationRevocation',
    summary: 'Get an Agent authorization revocation',
    request: { params: z.object({ authorizationId: z.string() }) },
    response: z.object({ authorizationId: z.string(), status: z.string() }),
  },
  {
    method: 'put',
    path: '/access/authorizations/{authorizationId}/revocation',
    operationId: 'replaceAgentAuthorizationRevocation',
    summary: 'Create or replace an Agent authorization revocation',
    request: { params: z.object({ authorizationId: z.string() }) },
    response: z.object({ authorizationId: z.string(), status: z.literal('revoked') }),
  },
  {
    method: 'post',
    path: '/access/authorizations/{authorizationId}/credentials',
    operationId: 'createAgentAuthorizationCredential',
    summary: 'Create a temporary credential for an Agent authorization',
    security: [{ dpop: ['access-authorizations:issue'] }],
    request: {
      params: z.object({ authorizationId: z.string() }),
      body: jsonBody(targetCredentialProofSchema),
    },
    response: targetTokenSchema,
  },
  {
    method: 'get',
    path: '/agents/{agentId}/recovery',
    operationId: 'getAgentRecovery',
    summary: 'Get an Agent recovery',
    request: { params: z.object({ agentId: z.string() }) },
    response: agentRecoverySchema,
    security: [{ dpop: ['agent:read'] }, { dpop: ['agents:read'] }, { sessionCookie: ['agents:read'] }],
  },
  {
    method: 'put',
    path: '/agents/{agentId}/recovery',
    operationId: 'replaceAgentRecovery',
    summary: 'Create or replace an Agent recovery',
    request: { params: z.object({ agentId: z.string() }) },
    response: agentRecoverySchema,
    security: [{ dpop: ['agent:write'] }, { dpop: ['agents:write'] }, { sessionCookie: ['agents:write'] }],
  },
  {
    method: 'get',
    path: '/agents/{agentId}/retirement',
    operationId: 'getAgentRetirement',
    summary: 'Get an Agent retirement',
    request: { params: z.object({ agentId: z.string() }) },
    response: z.object({ agentId: z.string(), status: z.string(), retiredAt: z.string().nullable() }),
    security: [{ dpop: ['agent:read'] }, { dpop: ['agents:read'] }, { sessionCookie: ['agents:read'] }],
  },
  {
    method: 'put',
    path: '/agents/{agentId}/retirement',
    operationId: 'replaceAgentRetirement',
    summary: 'Create or replace an Agent retirement',
    request: { params: z.object({ agentId: z.string() }) },
    noBody: true,
    security: [{ dpop: ['agent:write'] }, { dpop: ['agents:write'] }, { sessionCookie: ['agents:write'] }],
  },
  {
    method: 'delete',
    path: '/agents/{agentId}/retirement',
    operationId: 'deleteAgentRetirement',
    summary: 'Unsupported legacy retirement deletion',
    deprecated: true,
    request: { params: z.object({ agentId: z.string() }) },
    status: 410,
    response: managementErrorResponseSchema,
  },
  {
    method: 'get',
    path: '/realm/audit-events',
    operationId: 'listAgentAuditEvents',
    summary: 'List Agent audit events',
    request: { query: listAgentAuditEventsQuerySchema },
    response: auditEventsResponseSchema,
  },
]
