import {
  apiResourceSchema,
  apiResourcesResponseSchema,
  createApiResourceSchema,
  resourceServerSchema,
  resourceServersResponseSchema,
  updateApiResourceSchema,
} from '@shared/api/agent-api'
import { apiResourceContractResponseSchema } from '@shared/api/authorization'
import {
  addMemberRequestSchema,
  applicationAuthorizationRevocationSchema,
  applicationAuthorizationSchema,
  applicationIdParam,
  applicationResponseSchema,
  assignmentIdParam,
  authorizationIdParam,
  createApplicationRequestSchema,
  createApplicationResponseSchema,
  createInvitationRequestSchema,
  createManagementFederatedCredentialRequestSchema,
  createManagementFederatedCredentialResponseSchema,
  createOrganizationRequestSchema,
  createRoleAssignmentRequestSchema,
  createRoleRequestSchema,
  etagResponseHeader,
  federatedCredentialParam,
  ifMatchHeader,
  invitationParam,
  invitationResponseSchema,
  jsonBody,
  listApiResourcesQuerySchema,
  listApplicationAuthorizationsQuerySchema,
  listApplicationAuthorizationsResponseSchema,
  listApplicationsQuerySchema,
  listApplicationsResponseSchema,
  listClientSecretsResponseSchema,
  listInvitationsResponseSchema,
  listManagementFederatedCredentialsResponseSchema,
  listMembersResponseSchema,
  listOrganizationsResponseSchema,
  listRedirectUrisResponseSchema,
  listRoleAssignmentsQuerySchema,
  listRoleAssignmentsResponseSchema,
  listRolesResponseSchema,
  locationResponseHeader,
  type ManagementRouteConfig,
  memberParam,
  memberResponseSchema,
  organizationIdParam,
  organizationResponseSchema,
  paginationQuerySchema,
  replaceRedirectUrisRequestSchema,
  replaceRoleScopesRequestSchema,
  resourceServerIdParam,
  roleAssignmentResponseSchema,
  roleAssignmentRevocationSchema,
  roleIdParam,
  roleResponseSchema,
  roleScopesResponseSchema,
  rotateClientSecretResponseSchema,
  updateApplicationRequestSchema,
  updateManagementFederatedCredentialRequestSchema,
  updateMemberRequestSchema,
  updateOrganizationRequestSchema,
  updateRoleRequestSchema,
  z,
} from './helpers'

export const applicationAuthorizationRoutes: ManagementRouteConfig[] = [
  {
    method: 'get',
    path: '/applications',
    operationId: 'listApplications',
    summary: 'List applications',
    request: { query: listApplicationsQuerySchema },
    response: listApplicationsResponseSchema,
  },
  {
    method: 'post',
    path: '/applications',
    operationId: 'createApplication',
    summary: 'Create application',
    request: { body: jsonBody(createApplicationRequestSchema) },
    response: createApplicationResponseSchema,
    status: 201,
    responseHeaders: locationResponseHeader,
    errors: { 400: 'The Application representation is invalid.', 409: 'The Application already exists.' },
  },
  {
    method: 'get',
    path: '/access/consents',
    operationId: 'listApplicationConsents',
    summary: 'List application consents',
    request: { query: listApplicationAuthorizationsQuerySchema },
    response: listApplicationAuthorizationsResponseSchema,
    errors: { 400: 'The collection query is invalid.' },
  },
  {
    method: 'get',
    path: '/access/consents/{consentId}',
    operationId: 'getApplicationConsent',
    summary: 'Get an application consent',
    request: { params: authorizationIdParam },
    response: applicationAuthorizationSchema,
    errors: { 404: 'The Application authorization was not found.' },
  },
  {
    method: 'put',
    path: '/access/consents/{consentId}/revocation',
    operationId: 'replaceApplicationConsentRevocation',
    summary: 'Create or replace an application consent revocation',
    request: { params: authorizationIdParam },
    response: applicationAuthorizationRevocationSchema,
    errors: { 404: 'The Application authorization was not found.' },
  },
  {
    method: 'get',
    path: '/access/consents/{consentId}/revocation',
    operationId: 'getApplicationConsentRevocation',
    summary: 'Get an application consent revocation',
    request: { params: authorizationIdParam },
    response: applicationAuthorizationRevocationSchema.nullable(),
  },
  {
    method: 'get',
    path: '/applications/{applicationId}',
    operationId: 'getApplication',
    summary: 'Get application',
    request: { params: applicationIdParam },
    response: applicationResponseSchema,
  },
  {
    method: 'patch',
    path: '/applications/{applicationId}',
    operationId: 'updateApplication',
    summary: 'Update application',
    request: { params: applicationIdParam, body: jsonBody(updateApplicationRequestSchema) },
    response: applicationResponseSchema,
  },
  {
    method: 'delete',
    path: '/applications/{applicationId}',
    operationId: 'deleteApplication',
    summary: 'Delete application',
    request: { params: applicationIdParam },
    noBody: true,
  },
  {
    method: 'get',
    path: '/applications/{applicationId}/redirect-uris',
    operationId: 'listRedirectUris',
    summary: 'List application redirect URIs',
    request: { params: applicationIdParam, query: paginationQuerySchema },
    response: listRedirectUrisResponseSchema,
  },
  {
    method: 'put',
    path: '/applications/{applicationId}/redirect-uris',
    operationId: 'replaceRedirectUris',
    summary: 'Replace application redirect URIs',
    request: { params: applicationIdParam, body: jsonBody(replaceRedirectUrisRequestSchema) },
    response: listRedirectUrisResponseSchema,
  },
  {
    method: 'get',
    path: '/applications/{applicationId}/client-secrets',
    operationId: 'listClientSecrets',
    summary: 'List application client secrets',
    request: { params: applicationIdParam, query: paginationQuerySchema },
    response: listClientSecretsResponseSchema,
  },
  {
    method: 'post',
    path: '/applications/{applicationId}/client-secrets',
    operationId: 'createClientSecret',
    summary: 'Create an application client secret',
    request: { params: applicationIdParam },
    response: rotateClientSecretResponseSchema,
    status: 201,
  },
  {
    method: 'get',
    path: '/applications/{applicationId}/federated-credentials',
    operationId: 'listFederatedCredentials',
    summary: 'List application federated credentials',
    request: { params: applicationIdParam },
    response: listManagementFederatedCredentialsResponseSchema,
  },
  {
    method: 'post',
    path: '/applications/{applicationId}/federated-credentials',
    operationId: 'createFederatedCredential',
    summary: 'Create application federated credential',
    request: { params: applicationIdParam, body: jsonBody(createManagementFederatedCredentialRequestSchema) },
    response: createManagementFederatedCredentialResponseSchema,
    status: 201,
  },
  {
    method: 'get',
    path: '/applications/{applicationId}/federated-credentials/{credentialId}',
    operationId: 'getFederatedCredential',
    summary: 'Get application federated credential',
    request: { params: federatedCredentialParam },
    response: createManagementFederatedCredentialResponseSchema,
  },
  {
    method: 'patch',
    path: '/applications/{applicationId}/federated-credentials/{credentialId}',
    operationId: 'updateFederatedCredential',
    summary: 'Update application federated credential',
    request: { params: federatedCredentialParam, body: jsonBody(updateManagementFederatedCredentialRequestSchema) },
    response: createManagementFederatedCredentialResponseSchema,
  },
  {
    method: 'delete',
    path: '/applications/{applicationId}/federated-credentials/{credentialId}',
    operationId: 'deleteFederatedCredential',
    summary: 'Delete application federated credential',
    request: { params: federatedCredentialParam },
    noBody: true,
  },

  {
    method: 'get',
    path: '/resource-servers',
    operationId: 'listResourceServers',
    summary: 'List Resource Servers',
    request: { query: listApiResourcesQuerySchema },
    response: z.union([apiResourcesResponseSchema, resourceServersResponseSchema]),
  },
  {
    method: 'post',
    path: '/resource-servers',
    operationId: 'createResourceServer',
    summary: 'Create a Resource Server',
    request: { body: jsonBody(createApiResourceSchema) },
    response: apiResourceSchema,
    status: 201,
    responseHeaders: locationResponseHeader,
  },
  {
    method: 'get',
    path: '/resource-servers/{resourceServerId}',
    operationId: 'getResourceServer',
    summary: 'Get a Resource Server',
    request: { params: resourceServerIdParam },
    response: z.union([apiResourceSchema, resourceServerSchema]),
  },
  {
    method: 'get',
    path: '/resource-servers/{resourceServerId}/contract',
    operationId: 'getResourceServerContract',
    summary: 'Get a Resource Server contract',
    request: { params: resourceServerIdParam },
    response: apiResourceContractResponseSchema,
    errors: {
      404: 'The API resource was not found.',
      502: 'The Resource Server contract could not be retrieved or validated.',
    },
  },
  {
    method: 'patch',
    path: '/resource-servers/{resourceServerId}',
    operationId: 'updateResourceServer',
    summary: 'Update a Resource Server',
    request: { params: resourceServerIdParam, body: jsonBody(updateApiResourceSchema) },
    response: apiResourceSchema,
  },
  {
    method: 'delete',
    path: '/resource-servers/{resourceServerId}',
    operationId: 'deleteResourceServer',
    summary: 'Delete a Resource Server',
    request: { params: resourceServerIdParam },
    noBody: true,
    errors: {
      409: 'The API resource has authorization history and cannot be permanently deleted.',
    },
  },
  {
    method: 'put',
    path: '/resource-servers/{resourceServerId}/archival',
    operationId: 'replaceResourceServerArchival',
    summary: 'Create or replace a Resource Server archival',
    request: { params: resourceServerIdParam },
    response: apiResourceSchema,
  },
  {
    method: 'get',
    path: '/resource-servers/{resourceServerId}/archival',
    operationId: 'getResourceServerArchival',
    summary: 'Get a Resource Server archival',
    request: { params: resourceServerIdParam },
    response: z.object({ resourceServerId: z.string(), archivedAt: z.iso.datetime().nullable() }),
  },
  {
    method: 'delete',
    path: '/resource-servers/{resourceServerId}/archival',
    operationId: 'deleteResourceServerArchival',
    summary: 'Delete a Resource Server archival',
    request: { params: resourceServerIdParam },
    response: apiResourceSchema,
  },

  {
    method: 'get',
    path: '/organizations',
    operationId: 'listOrganizations',
    summary: 'List organizations',
    request: { query: paginationQuerySchema },
    response: listOrganizationsResponseSchema,
  },
  {
    method: 'post',
    path: '/organizations',
    operationId: 'createOrganization',
    summary: 'Create organization',
    request: { body: jsonBody(createOrganizationRequestSchema) },
    response: organizationResponseSchema,
    status: 201,
    responseHeaders: locationResponseHeader,
  },
  {
    method: 'get',
    path: '/organizations/{organizationId}',
    operationId: 'getOrganization',
    summary: 'Get organization',
    request: { params: organizationIdParam },
    response: organizationResponseSchema,
  },
  {
    method: 'patch',
    path: '/organizations/{organizationId}',
    operationId: 'updateOrganization',
    summary: 'Update organization',
    request: { params: organizationIdParam, body: jsonBody(updateOrganizationRequestSchema) },
    response: organizationResponseSchema,
  },
  {
    method: 'delete',
    path: '/organizations/{organizationId}',
    operationId: 'deleteOrganization',
    summary: 'Delete organization',
    request: { params: organizationIdParam },
    noBody: true,
  },
  {
    method: 'get',
    path: '/organizations/{organizationId}/members',
    operationId: 'listOrganizationMembers',
    summary: 'List organization members',
    request: { params: organizationIdParam, query: paginationQuerySchema },
    response: listMembersResponseSchema,
  },
  {
    method: 'post',
    path: '/organizations/{organizationId}/members',
    operationId: 'createOrganizationMember',
    summary: 'Create organization member',
    request: { params: organizationIdParam, body: jsonBody(addMemberRequestSchema) },
    response: memberResponseSchema,
    status: 201,
    responseHeaders: locationResponseHeader,
  },
  {
    method: 'get',
    path: '/organizations/{organizationId}/members/{memberId}',
    operationId: 'getOrganizationMember',
    summary: 'Get organization member',
    request: { params: memberParam },
    response: memberResponseSchema,
  },
  {
    method: 'patch',
    path: '/organizations/{organizationId}/members/{memberId}',
    operationId: 'updateOrganizationMember',
    summary: 'Update organization member',
    request: { params: memberParam, body: jsonBody(updateMemberRequestSchema) },
    response: z.object({ member: z.unknown() }),
  },
  {
    method: 'delete',
    path: '/organizations/{organizationId}/members/{memberId}',
    operationId: 'deleteOrganizationMember',
    summary: 'Delete organization member',
    request: { params: memberParam },
    noBody: true,
  },
  {
    method: 'get',
    path: '/organizations/{organizationId}/invitations',
    operationId: 'listOrganizationInvitations',
    summary: 'List organization invitations',
    request: { params: organizationIdParam, query: paginationQuerySchema },
    response: listInvitationsResponseSchema,
  },
  {
    method: 'post',
    path: '/organizations/{organizationId}/invitations',
    operationId: 'createOrganizationInvitation',
    summary: 'Create organization invitation',
    request: { params: organizationIdParam, body: jsonBody(createInvitationRequestSchema) },
    response: invitationResponseSchema,
    status: 201,
    responseHeaders: locationResponseHeader,
  },
  {
    method: 'get',
    path: '/organizations/{organizationId}/invitations/{invitationId}',
    operationId: 'getOrganizationInvitation',
    summary: 'Get organization invitation',
    request: { params: invitationParam },
    response: invitationResponseSchema,
  },
  {
    method: 'delete',
    path: '/organizations/{organizationId}/invitations/{invitationId}',
    operationId: 'deleteOrganizationInvitation',
    summary: 'Delete organization invitation',
    request: { params: invitationParam },
    noBody: true,
  },

  {
    method: 'get',
    path: '/access/roles',
    operationId: 'listRoles',
    summary: 'List roles',
    request: { query: paginationQuerySchema },
    response: listRolesResponseSchema,
  },
  {
    method: 'post',
    path: '/access/roles',
    operationId: 'createRole',
    summary: 'Create role',
    request: { body: jsonBody(createRoleRequestSchema) },
    response: roleResponseSchema,
    status: 201,
    responseHeaders: locationResponseHeader,
  },
  {
    method: 'get',
    path: '/access/roles/{roleId}',
    operationId: 'getRole',
    summary: 'Get role',
    request: { params: roleIdParam },
    response: roleResponseSchema,
  },
  {
    method: 'patch',
    path: '/access/roles/{roleId}',
    operationId: 'updateRole',
    summary: 'Update role',
    request: { params: roleIdParam, body: jsonBody(updateRoleRequestSchema) },
    response: roleResponseSchema,
  },
  {
    method: 'delete',
    path: '/access/roles/{roleId}',
    operationId: 'deleteRole',
    summary: 'Delete role',
    request: { params: roleIdParam },
    noBody: true,
  },
  {
    method: 'get',
    path: '/access/roles/{roleId}/scopes',
    operationId: 'listRoleScopes',
    summary: 'List Role scopes',
    request: { params: roleIdParam },
    response: roleScopesResponseSchema,
    responseHeaders: etagResponseHeader,
    errors: { 404: 'The Role was not found.' },
  },
  {
    method: 'put',
    path: '/access/roles/{roleId}/scopes',
    operationId: 'replaceRoleScopes',
    summary: 'Replace Role scopes',
    request: { params: roleIdParam, headers: ifMatchHeader, body: jsonBody(replaceRoleScopesRequestSchema) },
    response: roleScopesResponseSchema,
    responseHeaders: etagResponseHeader,
    errors: {
      400: 'A Role permission is invalid.',
      404: 'The Role or Resource server was not found.',
      412: 'The Role permissions changed after the supplied entity tag was read.',
      428: 'If-Match is required.',
      502: 'A Resource server contract could not be loaded.',
    },
  },
  {
    method: 'get',
    path: '/access/assignments',
    operationId: 'listRoleAssignments',
    summary: 'List role assignments',
    request: { query: listRoleAssignmentsQuerySchema },
    response: listRoleAssignmentsResponseSchema,
  },
  {
    method: 'post',
    path: '/access/assignments',
    operationId: 'createRoleAssignment',
    summary: 'Create role assignment',
    request: { body: jsonBody(createRoleAssignmentRequestSchema) },
    response: roleAssignmentResponseSchema,
    status: 201,
    responseHeaders: locationResponseHeader,
    errors: {
      400: 'The Role assignment is invalid.',
      404: 'The Role, subject, or Organization was not found.',
      409: 'An active Role assignment already exists for this context.',
    },
  },
  {
    method: 'get',
    path: '/access/assignments/{assignmentId}',
    operationId: 'getRoleAssignment',
    summary: 'Get a Role assignment',
    request: { params: assignmentIdParam },
    response: roleAssignmentResponseSchema,
    errors: { 404: 'The Role assignment was not found.' },
  },
  {
    method: 'put',
    path: '/access/assignments/{assignmentId}/revocation',
    operationId: 'putRoleAssignmentRevocation',
    summary: 'Create or replace a Role assignment revocation',
    request: { params: assignmentIdParam },
    response: roleAssignmentRevocationSchema,
    errors: { 404: 'The Role assignment was not found.' },
  },
  {
    method: 'get',
    path: '/access/assignments/{assignmentId}/revocation',
    operationId: 'getRoleAssignmentRevocation',
    summary: 'Get a Role assignment revocation',
    request: { params: assignmentIdParam },
    response: roleAssignmentRevocationSchema.nullable(),
  },
]
