import {
  createApiResourceSchema,
  resourceServerSchema,
  resourceServersResponseSchema,
  updateApiResourceSchema,
} from '@shared/api/agent-api'
import {
  apiResourceContractResponseSchema,
  applicationScopeGrantResponseSchema,
  createApplicationScopeGrantRequestSchema,
  createUserScopeGrantRequestSchema,
  listApplicationScopeGrantsResponseSchema,
  listScopeGrantsQuerySchema,
  listUserScopeGrantsResponseSchema,
  userScopeGrantResponseSchema,
} from '@shared/api/authorization'
import {
  addMemberRequestSchema,
  applicationAuthorizationRevocationSchema,
  applicationAuthorizationSchema,
  applicationIdParam,
  applicationResponseSchema,
  authorizationIdParam,
  createApplicationRequestSchema,
  createApplicationResponseSchema,
  createInvitationRequestSchema,
  createManagementFederatedCredentialRequestSchema,
  createManagementFederatedCredentialResponseSchema,
  createOrganizationRequestSchema,
  createRoleRequestSchema,
  federatedCredentialParam,
  invitationParam,
  invitationResponseSchema,
  jsonBody,
  listApiResourcesQuerySchema,
  listApplicationAuthorizationsQuerySchema,
  listApplicationAuthorizationsResponseSchema,
  listApplicationsQuerySchema,
  listApplicationsResponseSchema,
  listClientSecretsResponseSchema,
  listInvitationsResponseSchema,
  listManagementFederatedCredentialsResponseSchema,
  listMembersResponseSchema,
  listOrganizationsResponseSchema,
  listRedirectUrisResponseSchema,
  listRolesResponseSchema,
  locationResponseHeader,
  type ManagementRouteConfig,
  memberParam,
  memberResponseSchema,
  memberRolesResponseSchema,
  organizationIdParam,
  organizationResponseSchema,
  paginationQuerySchema,
  replaceMemberRolesRequestSchema,
  replaceRedirectUrisRequestSchema,
  resourceServerConformanceErrorResponseSchema,
  resourceServerIdParam,
  resourceServerMutationErrorResponseSchema,
  roleKeyParam,
  roleResponseSchema,
  rotateClientSecretResponseSchema,
  updateApplicationRequestSchema,
  updateManagementFederatedCredentialRequestSchema,
  updateMemberRequestSchema,
  updateOrganizationRequestSchema,
  updateRoleRequestSchema,
  z,
} from './helpers'

export const applicationAuthorizationRoutes: ManagementRouteConfig[] = [
  {
    method: 'get',
    path: '/applications',
    operationId: 'listApplications',
    summary: 'List applications',
    request: { query: listApplicationsQuerySchema },
    response: listApplicationsResponseSchema,
  },
  {
    method: 'post',
    path: '/applications',
    operationId: 'createApplication',
    summary: 'Create application',
    request: { body: jsonBody(createApplicationRequestSchema) },
    response: createApplicationResponseSchema,
    status: 201,
    responseHeaders: locationResponseHeader,
    errors: { 400: 'The Application representation is invalid.', 409: 'The Application already exists.' },
  },
  {
    method: 'get',
    path: '/access/consents',
    operationId: 'listApplicationConsents',
    summary: 'List application consents',
    request: { query: listApplicationAuthorizationsQuerySchema },
    response: listApplicationAuthorizationsResponseSchema,
    errors: { 400: 'The collection query is invalid.' },
  },
  {
    method: 'get',
    path: '/access/consents/{consentId}',
    operationId: 'getApplicationConsent',
    summary: 'Get an application consent',
    request: { params: authorizationIdParam },
    response: applicationAuthorizationSchema,
    errors: { 404: 'The Application authorization was not found.' },
  },
  {
    method: 'put',
    path: '/access/consents/{consentId}/revocation',
    operationId: 'replaceApplicationConsentRevocation',
    summary: 'Create or replace an application consent revocation',
    request: { params: authorizationIdParam },
    response: applicationAuthorizationRevocationSchema,
    errors: { 404: 'The Application authorization was not found.' },
  },
  {
    method: 'get',
    path: '/access/consents/{consentId}/revocation',
    operationId: 'getApplicationConsentRevocation',
    summary: 'Get an application consent revocation',
    request: { params: authorizationIdParam },
    response: applicationAuthorizationRevocationSchema.nullable(),
  },
  {
    method: 'get',
    path: '/applications/{applicationId}',
    operationId: 'getApplication',
    summary: 'Get application',
    request: { params: applicationIdParam },
    response: applicationResponseSchema,
  },
  {
    method: 'patch',
    path: '/applications/{applicationId}',
    operationId: 'updateApplication',
    summary: 'Update application',
    request: { params: applicationIdParam, body: jsonBody(updateApplicationRequestSchema) },
    response: applicationResponseSchema,
  },
  {
    method: 'delete',
    path: '/applications/{applicationId}',
    operationId: 'deleteApplication',
    summary: 'Delete application',
    request: { params: applicationIdParam },
    noBody: true,
  },
  {
    method: 'get',
    path: '/applications/{applicationId}/redirect-uris',
    operationId: 'listRedirectUris',
    summary: 'List application redirect URIs',
    request: { params: applicationIdParam, query: paginationQuerySchema },
    response: listRedirectUrisResponseSchema,
  },
  {
    method: 'put',
    path: '/applications/{applicationId}/redirect-uris',
    operationId: 'replaceRedirectUris',
    summary: 'Replace application redirect URIs',
    request: { params: applicationIdParam, body: jsonBody(replaceRedirectUrisRequestSchema) },
    response: listRedirectUrisResponseSchema,
  },
  {
    method: 'get',
    path: '/applications/{applicationId}/client-secrets',
    operationId: 'listClientSecrets',
    summary: 'List application client secrets',
    request: { params: applicationIdParam, query: paginationQuerySchema },
    response: listClientSecretsResponseSchema,
  },
  {
    method: 'post',
    path: '/applications/{applicationId}/client-secrets',
    operationId: 'createClientSecret',
    summary: 'Create an application client secret',
    request: { params: applicationIdParam },
    response: rotateClientSecretResponseSchema,
    status: 201,
  },
  {
    method: 'get',
    path: '/applications/{applicationId}/federated-credentials',
    operationId: 'listFederatedCredentials',
    summary: 'List application federated credentials',
    request: { params: applicationIdParam },
    response: listManagementFederatedCredentialsResponseSchema,
  },
  {
    method: 'post',
    path: '/applications/{applicationId}/federated-credentials',
    operationId: 'createFederatedCredential',
    summary: 'Create application federated credential',
    request: { params: applicationIdParam, body: jsonBody(createManagementFederatedCredentialRequestSchema) },
    response: createManagementFederatedCredentialResponseSchema,
    status: 201,
  },
  {
    method: 'get',
    path: '/applications/{applicationId}/federated-credentials/{credentialId}',
    operationId: 'getFederatedCredential',
    summary: 'Get application federated credential',
    request: { params: federatedCredentialParam },
    response: createManagementFederatedCredentialResponseSchema,
  },
  {
    method: 'patch',
    path: '/applications/{applicationId}/federated-credentials/{credentialId}',
    operationId: 'updateFederatedCredential',
    summary: 'Update application federated credential',
    request: { params: federatedCredentialParam, body: jsonBody(updateManagementFederatedCredentialRequestSchema) },
    response: createManagementFederatedCredentialResponseSchema,
  },
  {
    method: 'delete',
    path: '/applications/{applicationId}/federated-credentials/{credentialId}',
    operationId: 'deleteFederatedCredential',
    summary: 'Delete application federated credential',
    request: { params: federatedCredentialParam },
    noBody: true,
  },

  {
    method: 'get',
    path: '/resource-servers',
    operationId: 'listResourceServers',
    summary: 'List Resource Servers',
    request: { query: listApiResourcesQuerySchema },
    response: resourceServersResponseSchema,
  },
  {
    method: 'post',
    path: '/resource-servers',
    operationId: 'createResourceServer',
    summary: 'Create a Resource Server',
    request: { body: jsonBody(createApiResourceSchema) },
    response: resourceServerSchema,
    status: 201,
    responseHeaders: locationResponseHeader,
    errors: {
      400: {
        description: 'The Resource Server does not satisfy the Realmroot integration profile.',
        schema: resourceServerMutationErrorResponseSchema,
      },
      502: {
        description: 'The Resource Server could not be reached for conformance validation.',
        schema: resourceServerConformanceErrorResponseSchema,
      },
    },
  },
  {
    method: 'get',
    path: '/resource-servers/{resourceServerId}',
    operationId: 'getResourceServer',
    summary: 'Get a Resource Server',
    request: { params: resourceServerIdParam },
    response: resourceServerSchema,
  },
  {
    method: 'get',
    path: '/resource-servers/{resourceServerId}/contract',
    operationId: 'getResourceServerContract',
    summary: 'Get a Resource Server contract',
    request: { params: resourceServerIdParam },
    response: apiResourceContractResponseSchema,
    errors: {
      404: 'The API resource was not found.',
      502: 'The Resource Server contract could not be retrieved or validated.',
    },
  },
  {
    method: 'put',
    path: '/resource-servers/{resourceServerId}/scope-registry',
    operationId: 'replaceResourceServerScopeRegistry',
    summary: 'Synchronize a Resource Server scope registry',
    request: { params: resourceServerIdParam },
    response: resourceServerSchema,
    noBody: true,
    errors: {
      400: {
        description: 'The Resource Server is inactive, system-managed, or does not satisfy the integration profile.',
        schema: resourceServerMutationErrorResponseSchema,
      },
      502: {
        description: 'The Resource Server scope registry could not be synchronized.',
        schema: resourceServerConformanceErrorResponseSchema,
      },
    },
  },
  {
    method: 'patch',
    path: '/resource-servers/{resourceServerId}',
    operationId: 'updateResourceServer',
    summary: 'Update a Resource Server',
    request: { params: resourceServerIdParam, body: jsonBody(updateApiResourceSchema) },
    response: resourceServerSchema,
    errors: {
      400: {
        description: 'The Resource Server does not satisfy the Realmroot integration profile.',
        schema: resourceServerMutationErrorResponseSchema,
      },
      502: {
        description: 'The Resource Server could not be reached for conformance validation.',
        schema: resourceServerConformanceErrorResponseSchema,
      },
    },
  },
  {
    method: 'delete',
    path: '/resource-servers/{resourceServerId}',
    operationId: 'deleteResourceServer',
    summary: 'Delete a Resource Server',
    request: { params: resourceServerIdParam },
    noBody: true,
  },

  {
    method: 'get',
    path: '/users/{userId}/scope-grants',
    operationId: 'listUserScopeGrants',
    summary: 'List a User’s direct scope grants',
    security: [{ sessionCookie: ['roles:read'] }],
    request: { params: z.object({ userId: z.string() }), query: listScopeGrantsQuerySchema },
    response: listUserScopeGrantsResponseSchema,
    errors: { 400: 'The collection query is invalid.' },
  },
  {
    method: 'post',
    path: '/users/{userId}/scope-grants',
    operationId: 'createUserScopeGrant',
    summary: 'Create a direct User scope grant',
    security: [{ sessionCookie: ['roles:write'] }],
    request: { params: z.object({ userId: z.string() }), body: jsonBody(createUserScopeGrantRequestSchema) },
    response: userScopeGrantResponseSchema,
    status: 201,
    responseHeaders: locationResponseHeader,
    errors: { 400: 'The request body is invalid.', 404: 'The User or Resource Server was not found.' },
  },
  {
    method: 'get',
    path: '/users/{userId}/scope-grants/{grantId}',
    operationId: 'getUserScopeGrant',
    summary: 'Get a direct User scope grant',
    security: [{ sessionCookie: ['roles:read'] }],
    request: { params: z.object({ userId: z.string(), grantId: z.string() }) },
    response: userScopeGrantResponseSchema,
    errors: { 404: 'The User scope grant was not found.' },
  },
  {
    method: 'delete',
    path: '/users/{userId}/scope-grants/{grantId}',
    operationId: 'deleteUserScopeGrant',
    summary: 'Delete a direct User scope grant',
    security: [{ sessionCookie: ['roles:write'] }],
    request: { params: z.object({ userId: z.string(), grantId: z.string() }) },
    noBody: true,
    errors: { 404: 'The User scope grant was not found.' },
  },
  {
    method: 'get',
    path: '/applications/{applicationId}/scope-grants',
    operationId: 'listApplicationScopeGrants',
    summary: 'List an Application’s direct scope grants',
    security: [{ sessionCookie: ['applications:read'] }],
    request: { params: z.object({ applicationId: z.string() }), query: listScopeGrantsQuerySchema },
    response: listApplicationScopeGrantsResponseSchema,
    errors: { 400: 'The collection query is invalid.', 404: 'The Application was not found.' },
  },
  {
    method: 'post',
    path: '/applications/{applicationId}/scope-grants',
    operationId: 'createApplicationScopeGrant',
    summary: 'Create a direct Application scope grant',
    security: [{ sessionCookie: ['applications:write'] }],
    request: {
      params: z.object({ applicationId: z.string() }),
      body: jsonBody(createApplicationScopeGrantRequestSchema),
    },
    response: applicationScopeGrantResponseSchema,
    status: 201,
    responseHeaders: locationResponseHeader,
    errors: { 400: 'The request body is invalid.', 404: 'The Application or Resource Server was not found.' },
  },
  {
    method: 'get',
    path: '/applications/{applicationId}/scope-grants/{grantId}',
    operationId: 'getApplicationScopeGrant',
    summary: 'Get a direct Application scope grant',
    security: [{ sessionCookie: ['applications:read'] }],
    request: { params: z.object({ applicationId: z.string(), grantId: z.string() }) },
    response: applicationScopeGrantResponseSchema,
    errors: { 404: 'The Application scope grant was not found.' },
  },
  {
    method: 'delete',
    path: '/applications/{applicationId}/scope-grants/{grantId}',
    operationId: 'deleteApplicationScopeGrant',
    summary: 'Delete a direct Application scope grant',
    security: [{ sessionCookie: ['applications:write'] }],
    request: { params: z.object({ applicationId: z.string(), grantId: z.string() }) },
    noBody: true,
    errors: { 404: 'The Application scope grant was not found.' },
  },

  {
    method: 'get',
    path: '/organizations',
    operationId: 'listOrganizations',
    summary: 'List organizations',
    request: { query: paginationQuerySchema },
    response: listOrganizationsResponseSchema,
  },
  {
    method: 'post',
    path: '/organizations',
    operationId: 'createOrganization',
    summary: 'Create organization',
    request: { body: jsonBody(createOrganizationRequestSchema) },
    response: organizationResponseSchema,
    status: 201,
    responseHeaders: locationResponseHeader,
  },
  {
    method: 'get',
    path: '/organizations/{organizationId}',
    operationId: 'getOrganization',
    summary: 'Get organization',
    request: { params: organizationIdParam },
    response: organizationResponseSchema,
  },
  {
    method: 'patch',
    path: '/organizations/{organizationId}',
    operationId: 'updateOrganization',
    summary: 'Update organization',
    request: { params: organizationIdParam, body: jsonBody(updateOrganizationRequestSchema) },
    response: organizationResponseSchema,
  },
  {
    method: 'delete',
    path: '/organizations/{organizationId}',
    operationId: 'deleteOrganization',
    summary: 'Delete organization',
    request: { params: organizationIdParam },
    noBody: true,
  },
  {
    method: 'get',
    path: '/organizations/{organizationId}/members',
    operationId: 'listOrganizationMembers',
    summary: 'List organization members',
    request: { params: organizationIdParam, query: paginationQuerySchema },
    response: listMembersResponseSchema,
  },
  {
    method: 'post',
    path: '/organizations/{organizationId}/members',
    operationId: 'createOrganizationMember',
    summary: 'Create organization member',
    request: { params: organizationIdParam, body: jsonBody(addMemberRequestSchema) },
    response: memberResponseSchema,
    status: 201,
    responseHeaders: locationResponseHeader,
  },
  {
    method: 'get',
    path: '/organizations/{organizationId}/members/{memberId}',
    operationId: 'getOrganizationMember',
    summary: 'Get organization member',
    request: { params: memberParam },
    response: memberResponseSchema,
  },
  {
    method: 'patch',
    path: '/organizations/{organizationId}/members/{memberId}',
    operationId: 'updateOrganizationMember',
    summary: 'Update organization member',
    request: { params: memberParam, body: jsonBody(updateMemberRequestSchema) },
    response: z.object({ member: z.unknown() }),
  },
  {
    method: 'delete',
    path: '/organizations/{organizationId}/members/{memberId}',
    operationId: 'deleteOrganizationMember',
    summary: 'Delete organization member',
    request: { params: memberParam },
    noBody: true,
  },
  {
    method: 'get',
    path: '/organizations/{organizationId}/invitations',
    operationId: 'listOrganizationInvitations',
    summary: 'List organization invitations',
    request: { params: organizationIdParam, query: paginationQuerySchema },
    response: listInvitationsResponseSchema,
  },
  {
    method: 'post',
    path: '/organizations/{organizationId}/invitations',
    operationId: 'createOrganizationInvitation',
    summary: 'Create organization invitation',
    request: { params: organizationIdParam, body: jsonBody(createInvitationRequestSchema) },
    response: invitationResponseSchema,
    status: 201,
    responseHeaders: locationResponseHeader,
  },
  {
    method: 'get',
    path: '/organizations/{organizationId}/invitations/{invitationId}',
    operationId: 'getOrganizationInvitation',
    summary: 'Get organization invitation',
    request: { params: invitationParam },
    response: invitationResponseSchema,
  },
  {
    method: 'delete',
    path: '/organizations/{organizationId}/invitations/{invitationId}',
    operationId: 'deleteOrganizationInvitation',
    summary: 'Delete organization invitation',
    request: { params: invitationParam },
    noBody: true,
  },

  {
    method: 'get',
    path: '/organizations/{organizationId}/roles',
    operationId: 'listOrganizationRoles',
    summary: 'List Organization Roles',
    request: { params: organizationIdParam, query: paginationQuerySchema },
    response: listRolesResponseSchema,
  },
  {
    method: 'post',
    path: '/organizations/{organizationId}/roles',
    operationId: 'createOrganizationRole',
    summary: 'Create an Organization Role',
    request: { params: organizationIdParam, body: jsonBody(createRoleRequestSchema) },
    response: roleResponseSchema,
    status: 201,
    responseHeaders: locationResponseHeader,
  },
  {
    method: 'get',
    path: '/organizations/{organizationId}/roles/{roleKey}',
    operationId: 'getOrganizationRole',
    summary: 'Get an Organization Role',
    request: { params: organizationIdParam.merge(roleKeyParam) },
    response: roleResponseSchema,
  },
  {
    method: 'patch',
    path: '/organizations/{organizationId}/roles/{roleKey}',
    operationId: 'updateOrganizationRole',
    summary: 'Update an Organization Role',
    request: { params: organizationIdParam.merge(roleKeyParam), body: jsonBody(updateRoleRequestSchema) },
    response: roleResponseSchema,
  },
  {
    method: 'delete',
    path: '/organizations/{organizationId}/roles/{roleKey}',
    operationId: 'deleteOrganizationRole',
    summary: 'Delete an Organization Role',
    request: { params: organizationIdParam.merge(roleKeyParam) },
    noBody: true,
  },
  {
    method: 'get',
    path: '/organizations/{organizationId}/members/{memberId}/roles',
    operationId: 'getOrganizationMemberRoles',
    summary: 'Get Organization member Roles',
    request: { params: memberParam },
    response: memberRolesResponseSchema,
  },
  {
    method: 'put',
    path: '/organizations/{organizationId}/members/{memberId}/roles',
    operationId: 'replaceOrganizationMemberRoles',
    summary: 'Replace Organization member Roles',
    request: { params: memberParam, body: jsonBody(replaceMemberRolesRequestSchema) },
    response: memberRolesResponseSchema,
  },
]
