import {
  connectorReadinessResponseSchema,
  createManagementConnectorRequestSchema,
  createWebhookEndpointRequestSchema,
  developerConsoleAccessPolicyResponseSchema,
  emailDeliveryConfigurationResponseSchema,
  etagResponseHeader,
  idempotencyKeyHeader,
  idempotencyReplayResponseHeader,
  idParam,
  ifMatchHeader,
  jsonBody,
  listConnectorTemplatesResponseSchema,
  listManagementConnectorsResponseSchema,
  listWebhookDeliveryAttemptsResponseSchema,
  listWebhookEndpointsQuerySchema,
  listWebhookEndpointsResponseSchema,
  listWebhookRequestsQuerySchema,
  listWebhookRequestsResponseSchema,
  locationResponseHeader,
  type ManagementRouteConfig,
  managementAccountCenterSettingsResponseSchema,
  managementBrandingSettingsResponseSchema,
  managementConnectorResponseSchema,
  managementReadinessResponseSchema,
  managementRealmResponseSchema,
  managementSignInSettingsResponseSchema,
  multipartBody,
  organizationCreationPolicyResponseSchema,
  paginationQuerySchema,
  replaceDeveloperConsoleAccessPolicyRequestSchema,
  replaceEmailDeliveryConfigurationRequestSchema,
  replaceOrganizationCreationPolicyRequestSchema,
  updateManagementAccountCenterSettingsRequestSchema,
  updateManagementBrandingSettingsRequestSchema,
  updateManagementConnectorRequestSchema,
  updateManagementRealmRequestSchema,
  updateManagementSignInSettingsRequestSchema,
  updateWebhookEndpointRequestSchema,
  uploadedAssetResponseSchema,
  webhookDeliveryAttemptSchema,
  webhookEndpointSchema,
  webhookEndpointSecretResponseSchema,
  webhookRequestSchema,
  z,
} from './helpers'

const webhookAttemptParam = z.object({
  id: z.string().openapi({ param: { name: 'id', in: 'path' } }),
  attemptId: z.string().openapi({ param: { name: 'attemptId', in: 'path' } }),
})

export const platformWebhookRoutes: ManagementRouteConfig[] = [
  {
    method: 'get',
    path: '/connectors',
    operationId: 'listConnectors',
    summary: 'List connectors',
    request: { query: paginationQuerySchema },
    response: listManagementConnectorsResponseSchema,
  },
  {
    method: 'post',
    path: '/connectors',
    operationId: 'createConnector',
    summary: 'Create connector',
    request: { body: jsonBody(createManagementConnectorRequestSchema) },
    response: managementConnectorResponseSchema,
    status: 201,
  },
  {
    method: 'get',
    path: '/connectors/{id}',
    operationId: 'getConnector',
    summary: 'Get connector',
    request: { params: idParam },
    response: managementConnectorResponseSchema,
  },
  {
    method: 'patch',
    path: '/connectors/{id}',
    operationId: 'updateConnector',
    summary: 'Update connector',
    request: { params: idParam, body: jsonBody(updateManagementConnectorRequestSchema) },
    response: managementConnectorResponseSchema,
  },
  {
    method: 'delete',
    path: '/connectors/{id}',
    operationId: 'deleteConnector',
    summary: 'Delete connector',
    request: { params: idParam },
    noBody: true,
  },
  {
    method: 'get',
    path: '/connectors/{id}/readiness',
    operationId: 'listConnectorReadiness',
    summary: 'Get connector readiness',
    request: { params: idParam },
    response: connectorReadinessResponseSchema,
  },
  {
    method: 'get',
    path: '/connectors/templates',
    operationId: 'listConnectorTemplates',
    summary: 'List connector templates',
    response: listConnectorTemplatesResponseSchema,
  },

  {
    method: 'get',
    path: '/sign-in-settings',
    operationId: 'getSignInSettings',
    summary: 'Get sign-in settings',
    response: managementSignInSettingsResponseSchema,
  },
  {
    method: 'get',
    path: '/realm',
    operationId: 'getRealm',
    summary: 'Get the Realm',
    response: managementRealmResponseSchema,
    responseHeaders: etagResponseHeader,
  },
  {
    method: 'patch',
    path: '/realm',
    operationId: 'updateRealm',
    summary: 'Update the Realm',
    request: { headers: ifMatchHeader, body: jsonBody(updateManagementRealmRequestSchema) },
    response: managementRealmResponseSchema,
    responseHeaders: etagResponseHeader,
    errors: {
      400: 'The Realm representation is invalid.',
      412: 'The Realm changed after it was read.',
      428: 'If-Match is required.',
    },
  },
  {
    method: 'get',
    path: '/email-delivery-configuration',
    operationId: 'getEmailDeliveryConfiguration',
    summary: 'Get the email delivery configuration',
    response: emailDeliveryConfigurationResponseSchema,
    responseHeaders: etagResponseHeader,
  },
  {
    method: 'put',
    path: '/email-delivery-configuration',
    operationId: 'replaceEmailDeliveryConfiguration',
    summary: 'Replace the email delivery configuration',
    request: { headers: ifMatchHeader, body: jsonBody(replaceEmailDeliveryConfigurationRequestSchema) },
    response: emailDeliveryConfigurationResponseSchema,
    responseHeaders: etagResponseHeader,
    errors: {
      400: 'The email delivery configuration is invalid.',
      409: 'The deployment cannot activate the selected email delivery provider.',
      412: 'The email delivery configuration changed after it was read.',
      428: 'If-Match is required.',
    },
  },
  {
    method: 'patch',
    path: '/sign-in-settings',
    operationId: 'updateSignInSettings',
    summary: 'Update sign-in settings',
    request: { body: jsonBody(updateManagementSignInSettingsRequestSchema) },
    response: managementSignInSettingsResponseSchema,
  },
  {
    method: 'get',
    path: '/branding-settings',
    operationId: 'getBrandingSettings',
    summary: 'Get branding settings',
    response: managementBrandingSettingsResponseSchema,
  },
  {
    method: 'patch',
    path: '/branding-settings',
    operationId: 'updateBrandingSettings',
    summary: 'Update branding settings',
    request: { body: jsonBody(updateManagementBrandingSettingsRequestSchema) },
    response: managementBrandingSettingsResponseSchema,
  },
  {
    method: 'get',
    path: '/account-center-settings',
    operationId: 'getAccountCenterSettings',
    summary: 'Get account center settings',
    response: managementAccountCenterSettingsResponseSchema,
  },
  {
    method: 'patch',
    path: '/account-center-settings',
    operationId: 'updateAccountCenterSettings',
    summary: 'Update account center settings',
    request: { body: jsonBody(updateManagementAccountCenterSettingsRequestSchema) },
    response: managementAccountCenterSettingsResponseSchema,
  },
  {
    method: 'get',
    path: '/organization-creation-policy',
    operationId: 'getOrganizationCreationPolicy',
    summary: 'Get the Organization creation policy',
    response: organizationCreationPolicyResponseSchema,
    responseHeaders: etagResponseHeader,
  },
  {
    method: 'put',
    path: '/organization-creation-policy',
    operationId: 'replaceOrganizationCreationPolicy',
    summary: 'Replace the Organization creation policy',
    request: { headers: ifMatchHeader, body: jsonBody(replaceOrganizationCreationPolicyRequestSchema) },
    response: organizationCreationPolicyResponseSchema,
    responseHeaders: etagResponseHeader,
    errors: {
      400: 'The Organization creation policy is invalid.',
      404: 'An approved user was not found.',
      412: 'The Organization creation policy changed after it was read.',
      428: 'If-Match is required.',
    },
  },
  {
    method: 'get',
    path: '/developer-console-access-policy',
    operationId: 'getDeveloperConsoleAccessPolicy',
    summary: 'Get the Developer Console access policy',
    response: developerConsoleAccessPolicyResponseSchema,
    responseHeaders: etagResponseHeader,
  },
  {
    method: 'put',
    path: '/developer-console-access-policy',
    operationId: 'replaceDeveloperConsoleAccessPolicy',
    summary: 'Replace the Developer Console access policy',
    request: { headers: ifMatchHeader, body: jsonBody(replaceDeveloperConsoleAccessPolicyRequestSchema) },
    response: developerConsoleAccessPolicyResponseSchema,
    responseHeaders: etagResponseHeader,
    errors: {
      400: 'The Developer Console access policy is invalid.',
      404: 'A selected Organization was not found.',
      412: 'The Developer Console access policy changed after it was read.',
      428: 'If-Match is required.',
    },
  },
  {
    method: 'post',
    path: '/branding/logo',
    operationId: 'uploadBrandingLogo',
    summary: 'Upload branding logo',
    request: { body: multipartBody() },
    response: uploadedAssetResponseSchema,
    status: 201,
  },
  {
    method: 'post',
    path: '/branding/favicon',
    operationId: 'uploadBrandingFavicon',
    summary: 'Upload branding favicon',
    request: { body: multipartBody() },
    response: uploadedAssetResponseSchema,
    status: 201,
  },
  {
    method: 'get',
    path: '/readiness',
    operationId: 'getReadiness',
    summary: 'Get deployment readiness',
    response: managementReadinessResponseSchema,
  },
  {
    method: 'get',
    path: '/webhooks/endpoints',
    operationId: 'listWebhookEndpoints',
    summary: 'List webhook endpoints',
    request: { query: listWebhookEndpointsQuerySchema },
    response: listWebhookEndpointsResponseSchema,
  },
  {
    method: 'post',
    path: '/webhooks/endpoints',
    operationId: 'createWebhookEndpoint',
    summary: 'Create webhook endpoint',
    request: { body: jsonBody(createWebhookEndpointRequestSchema) },
    response: webhookEndpointSecretResponseSchema,
    status: 201,
    responseHeaders: locationResponseHeader,
    errors: { 400: 'The webhook endpoint representation is invalid.' },
  },
  {
    method: 'get',
    path: '/webhooks/endpoints/{id}',
    operationId: 'getWebhookEndpoint',
    summary: 'Get webhook endpoint',
    request: { params: idParam },
    response: webhookEndpointSchema,
  },
  {
    method: 'patch',
    path: '/webhooks/endpoints/{id}',
    operationId: 'updateWebhookEndpoint',
    summary: 'Update webhook endpoint',
    request: { params: idParam, body: jsonBody(updateWebhookEndpointRequestSchema) },
    response: webhookEndpointSchema,
  },
  {
    method: 'delete',
    path: '/webhooks/endpoints/{id}',
    operationId: 'deleteWebhookEndpoint',
    summary: 'Delete webhook endpoint',
    request: { params: idParam },
    noBody: true,
  },
  {
    method: 'post',
    path: '/webhooks/endpoints/{id}/secrets',
    operationId: 'rotateWebhookEndpointSecret',
    summary: 'Rotate webhook endpoint secret',
    request: { params: idParam },
    response: webhookEndpointSecretResponseSchema,
    status: 201,
  },
  {
    method: 'get',
    path: '/webhooks/requests',
    operationId: 'listWebhookRequests',
    summary: 'List webhook requests',
    request: { query: listWebhookRequestsQuerySchema },
    response: listWebhookRequestsResponseSchema,
  },
  {
    method: 'get',
    path: '/webhooks/requests/{id}',
    operationId: 'getWebhookRequest',
    summary: 'Get webhook request',
    request: { params: idParam },
    response: webhookRequestSchema,
  },
  {
    method: 'get',
    path: '/webhooks/requests/{id}/attempts',
    operationId: 'listWebhookDeliveryAttempts',
    summary: 'List webhook delivery attempts',
    request: { params: idParam, query: paginationQuerySchema },
    response: listWebhookDeliveryAttemptsResponseSchema,
    errors: { 404: 'The webhook request was not found.' },
  },
  {
    method: 'post',
    path: '/webhooks/requests/{id}/attempts',
    operationId: 'createWebhookDeliveryAttempt',
    summary: 'Create a webhook delivery attempt',
    request: { params: idParam, headers: idempotencyKeyHeader },
    response: webhookDeliveryAttemptSchema,
    status: 201,
    responseHeaders: {
      ...locationResponseHeader,
      ...idempotencyReplayResponseHeader,
    },
    errors: {
      400: 'Idempotency-Key is missing or invalid.',
      404: 'The webhook request was not found.',
      409: 'The webhook request is already delivered.',
    },
  },
  {
    method: 'get',
    path: '/webhooks/requests/{id}/attempts/{attemptId}',
    operationId: 'getWebhookDeliveryAttempt',
    summary: 'Get a webhook delivery attempt',
    request: { params: webhookAttemptParam },
    response: webhookDeliveryAttemptSchema,
    errors: { 404: 'The webhook request or delivery attempt was not found.' },
  },
]
