name = "realmroot"
main = "./server/worker.ts"
compatibility_date = "2026-04-12"
compatibility_flags = ["nodejs_compat", "global_fetch_strictly_public"]
workers_dev = true
preview_urls = true

[[routes]]
pattern = "id.realmroot.dev"
custom_domain = true

[vars]
BETTER_AUTH_URL = "https://id.realmroot.dev"
TRUSTED_ORIGINS = "https://id.realmroot.dev"
WEBAUTHN_RP_ID = "id.realmroot.dev"
WEBAUTHN_ORIGINS = "https://id.realmroot.dev"

[assets]
binding = "ASSETS"
directory = "./dist/client"
not_found_handling = "single-page-application"
run_worker_first = ["/api/*", "/.well-known/*", "/oauth/account-connection/*"]

[[send_email]]
name = "EMAIL"

[[r2_buckets]]
binding = "ASSET_BUCKET"
bucket_name = "realmroot-assets"

[[d1_databases]]
binding = "DB"
database_name = "realmroot"
database_id = "b73b7c00-f774-4895-a4bc-db67af6d17f4"
migrations_dir = "./migrations"

[triggers]
crons = ["0 3 * * *"]

[observability]
enabled = true
