CREATE TABLE `site_settings` (
	`key` text PRIMARY KEY NOT NULL,
	`value` text NOT NULL,
	`revision` integer DEFAULT 1 NOT NULL,
	`updated_at` integer NOT NULL,
	CONSTRAINT "site_settings_value_json" CHECK(json_valid("site_settings"."value")),
	CONSTRAINT "site_settings_revision_positive" CHECK("site_settings"."revision" > 0)
);



-- Site configuration backfill and temporary old-Worker write synchronization.
CREATE TABLE site_settings_migration_guard (valid INTEGER CHECK(valid = 1));
INSERT INTO site_settings_migration_guard SELECT count(*) <= 1 FROM sign_in_experience;
INSERT INTO site_settings_migration_guard SELECT count(*) <= 1 FROM account_center_setting;
INSERT INTO site_settings_migration_guard SELECT count(*) <= 1 FROM branding_setting;
INSERT INTO site_settings_migration_guard SELECT count(*) <= 1 FROM email_service_config;
INSERT INTO site_settings_migration_guard SELECT count(*) = 0 FROM branding_setting WHERE application_id IS NOT NULL OR organization_id IS NOT NULL;
INSERT INTO site_settings_migration_guard SELECT count(*) = 0 FROM account_center_setting WHERE application_id IS NOT NULL;
INSERT INTO site_settings_migration_guard SELECT count(*) = 0 FROM deployment_setting;
DROP TABLE site_settings_migration_guard;
INSERT INTO site_settings (key,value,revision,updated_at) SELECT 'sign_in',json_object('passwordEnabled', json(CASE WHEN password_enabled THEN 'true' ELSE 'false' END), 'signupEnabled', json(CASE WHEN signup_enabled THEN 'true' ELSE 'false' END), 'socialLoginEnabled', json(CASE WHEN social_login_enabled THEN 'true' ELSE 'false' END), 'identifierFirst', json(CASE WHEN identifier_first THEN 'true' ELSE 'false' END), 'metadata', json(json_remove(COALESCE(metadata, '{}'), '$.securityPolicy', '$.developerPolicy', '$.copy', '$.supportUri'))),1,updated_at FROM sign_in_experience;
CREATE TRIGGER site_settings_sign_in_insert AFTER INSERT ON sign_in_experience BEGIN
INSERT INTO site_settings (key,value,revision,updated_at) SELECT 'sign_in',json_object('passwordEnabled', json(CASE WHEN password_enabled THEN 'true' ELSE 'false' END), 'signupEnabled', json(CASE WHEN signup_enabled THEN 'true' ELSE 'false' END), 'socialLoginEnabled', json(CASE WHEN social_login_enabled THEN 'true' ELSE 'false' END), 'identifierFirst', json(CASE WHEN identifier_first THEN 'true' ELSE 'false' END), 'metadata', json(json_remove(COALESCE(metadata, '{}'), '$.securityPolicy', '$.developerPolicy', '$.copy', '$.supportUri'))),1,updated_at FROM sign_in_experience WHERE id = NEW.id ON CONFLICT(key) DO UPDATE SET value=excluded.value,revision=site_settings.revision+1,updated_at=excluded.updated_at;
END;
CREATE TRIGGER site_settings_sign_in_update AFTER UPDATE ON sign_in_experience BEGIN
INSERT INTO site_settings (key,value,revision,updated_at) SELECT 'sign_in',json_object('passwordEnabled', json(CASE WHEN password_enabled THEN 'true' ELSE 'false' END), 'signupEnabled', json(CASE WHEN signup_enabled THEN 'true' ELSE 'false' END), 'socialLoginEnabled', json(CASE WHEN social_login_enabled THEN 'true' ELSE 'false' END), 'identifierFirst', json(CASE WHEN identifier_first THEN 'true' ELSE 'false' END), 'metadata', json(json_remove(COALESCE(metadata, '{}'), '$.securityPolicy', '$.developerPolicy', '$.copy', '$.supportUri'))),1,updated_at FROM sign_in_experience WHERE id = NEW.id ON CONFLICT(key) DO UPDATE SET value=excluded.value,revision=site_settings.revision+1,updated_at=excluded.updated_at;
END;
INSERT INTO site_settings (key,value,revision,updated_at) SELECT 'general',json_object('termsUri', terms_uri, 'privacyUri', privacy_uri, 'supportEmail', support_email, 'supportUri', json_extract(COALESCE(metadata, '{}'), '$.supportUri'), 'copy', json(COALESCE(json_extract(COALESCE(metadata, '{}'), '$.copy'), '{}')), 'defaultApplicationId', default_application_id, 'defaultRedirectUri', default_redirect_uri),1,updated_at FROM sign_in_experience;
CREATE TRIGGER site_settings_general_insert AFTER INSERT ON sign_in_experience BEGIN
INSERT INTO site_settings (key,value,revision,updated_at) SELECT 'general',json_object('termsUri', terms_uri, 'privacyUri', privacy_uri, 'supportEmail', support_email, 'supportUri', json_extract(COALESCE(metadata, '{}'), '$.supportUri'), 'copy', json(COALESCE(json_extract(COALESCE(metadata, '{}'), '$.copy'), '{}')), 'defaultApplicationId', default_application_id, 'defaultRedirectUri', default_redirect_uri),1,updated_at FROM sign_in_experience WHERE id = NEW.id ON CONFLICT(key) DO UPDATE SET value=excluded.value,revision=site_settings.revision+1,updated_at=excluded.updated_at;
END;
CREATE TRIGGER site_settings_general_update AFTER UPDATE ON sign_in_experience BEGIN
INSERT INTO site_settings (key,value,revision,updated_at) SELECT 'general',json_object('termsUri', terms_uri, 'privacyUri', privacy_uri, 'supportEmail', support_email, 'supportUri', json_extract(COALESCE(metadata, '{}'), '$.supportUri'), 'copy', json(COALESCE(json_extract(COALESCE(metadata, '{}'), '$.copy'), '{}')), 'defaultApplicationId', default_application_id, 'defaultRedirectUri', default_redirect_uri),1,updated_at FROM sign_in_experience WHERE id = NEW.id ON CONFLICT(key) DO UPDATE SET value=excluded.value,revision=site_settings.revision+1,updated_at=excluded.updated_at;
END;
INSERT INTO site_settings (key,value,revision,updated_at) SELECT 'security',json(COALESCE(json_extract(COALESCE(metadata, '{}'), '$.securityPolicy'), '{}')),1,updated_at FROM sign_in_experience;
CREATE TRIGGER site_settings_security_insert AFTER INSERT ON sign_in_experience BEGIN
INSERT INTO site_settings (key,value,revision,updated_at) SELECT 'security',json(COALESCE(json_extract(COALESCE(metadata, '{}'), '$.securityPolicy'), '{}')),1,updated_at FROM sign_in_experience WHERE id = NEW.id ON CONFLICT(key) DO UPDATE SET value=excluded.value,revision=site_settings.revision+1,updated_at=excluded.updated_at;
END;
CREATE TRIGGER site_settings_security_update AFTER UPDATE ON sign_in_experience BEGIN
INSERT INTO site_settings (key,value,revision,updated_at) SELECT 'security',json(COALESCE(json_extract(COALESCE(metadata, '{}'), '$.securityPolicy'), '{}')),1,updated_at FROM sign_in_experience WHERE id = NEW.id ON CONFLICT(key) DO UPDATE SET value=excluded.value,revision=site_settings.revision+1,updated_at=excluded.updated_at;
END;
INSERT INTO site_settings (key,value,revision,updated_at) SELECT 'developer',json_set(COALESCE(json_extract(COALESCE(metadata, '{}'), '$.developerPolicy'), '{}'), '$.selectedOrganizationIds', json((SELECT json_group_array(id) FROM organization WHERE json_extract(metadata, '$.realmroot.console.enabled') = 1))),1,updated_at FROM sign_in_experience;
CREATE TRIGGER site_settings_developer_insert AFTER INSERT ON sign_in_experience BEGIN
INSERT INTO site_settings (key,value,revision,updated_at) SELECT 'developer',json_set(COALESCE(json_extract(COALESCE(metadata, '{}'), '$.developerPolicy'), '{}'), '$.selectedOrganizationIds', json((SELECT json_group_array(id) FROM organization WHERE json_extract(metadata, '$.realmroot.console.enabled') = 1))),1,updated_at FROM sign_in_experience WHERE id = NEW.id ON CONFLICT(key) DO UPDATE SET value=excluded.value,revision=site_settings.revision+1,updated_at=excluded.updated_at;
END;
CREATE TRIGGER site_settings_developer_update AFTER UPDATE ON sign_in_experience BEGIN
INSERT INTO site_settings (key,value,revision,updated_at) SELECT 'developer',json_set(COALESCE(json_extract(COALESCE(metadata, '{}'), '$.developerPolicy'), '{}'), '$.selectedOrganizationIds', json((SELECT json_group_array(id) FROM organization WHERE json_extract(metadata, '$.realmroot.console.enabled') = 1))),1,updated_at FROM sign_in_experience WHERE id = NEW.id ON CONFLICT(key) DO UPDATE SET value=excluded.value,revision=site_settings.revision+1,updated_at=excluded.updated_at;
END;
INSERT INTO site_settings (key,value,revision,updated_at) SELECT 'account_center',json_object('profileEditingEnabled', json(CASE WHEN profile_editing_enabled THEN 'true' ELSE 'false' END), 'passwordChangeEnabled', json(CASE WHEN password_change_enabled THEN 'true' ELSE 'false' END), 'connectedAccountsEnabled', json(CASE WHEN connected_accounts_enabled THEN 'true' ELSE 'false' END), 'sessionsViewEnabled', json(CASE WHEN sessions_view_enabled THEN 'true' ELSE 'false' END), 'dangerZoneEnabled', json(CASE WHEN danger_zone_enabled THEN 'true' ELSE 'false' END), 'displayNameEditable', json(CASE WHEN COALESCE(json_extract(COALESCE(metadata, '{}'), '$.fieldPermissions.displayNameEditable'), 1) THEN 'true' ELSE 'false' END), 'usernameEditable', json(CASE WHEN COALESCE(json_extract(COALESCE(metadata, '{}'), '$.fieldPermissions.usernameEditable'), 1) THEN 'true' ELSE 'false' END), 'avatarEditable', json(CASE WHEN COALESCE(json_extract(COALESCE(metadata, '{}'), '$.fieldPermissions.avatarEditable'), 1) THEN 'true' ELSE 'false' END), 'emailChangeEnabled', json(CASE WHEN COALESCE(json_extract(COALESCE(metadata, '{}'), '$.fieldPermissions.emailChangeEnabled'), 1) THEN 'true' ELSE 'false' END), 'metadata', json(COALESCE(metadata, '{}'))),1,updated_at FROM account_center_setting;
CREATE TRIGGER site_settings_account_center_insert AFTER INSERT ON account_center_setting BEGIN
INSERT INTO site_settings (key,value,revision,updated_at) SELECT 'account_center',json_object('profileEditingEnabled', json(CASE WHEN profile_editing_enabled THEN 'true' ELSE 'false' END), 'passwordChangeEnabled', json(CASE WHEN password_change_enabled THEN 'true' ELSE 'false' END), 'connectedAccountsEnabled', json(CASE WHEN connected_accounts_enabled THEN 'true' ELSE 'false' END), 'sessionsViewEnabled', json(CASE WHEN sessions_view_enabled THEN 'true' ELSE 'false' END), 'dangerZoneEnabled', json(CASE WHEN danger_zone_enabled THEN 'true' ELSE 'false' END), 'displayNameEditable', json(CASE WHEN COALESCE(json_extract(COALESCE(metadata, '{}'), '$.fieldPermissions.displayNameEditable'), 1) THEN 'true' ELSE 'false' END), 'usernameEditable', json(CASE WHEN COALESCE(json_extract(COALESCE(metadata, '{}'), '$.fieldPermissions.usernameEditable'), 1) THEN 'true' ELSE 'false' END), 'avatarEditable', json(CASE WHEN COALESCE(json_extract(COALESCE(metadata, '{}'), '$.fieldPermissions.avatarEditable'), 1) THEN 'true' ELSE 'false' END), 'emailChangeEnabled', json(CASE WHEN COALESCE(json_extract(COALESCE(metadata, '{}'), '$.fieldPermissions.emailChangeEnabled'), 1) THEN 'true' ELSE 'false' END), 'metadata', json(COALESCE(metadata, '{}'))),1,updated_at FROM account_center_setting WHERE id = NEW.id ON CONFLICT(key) DO UPDATE SET value=excluded.value,revision=site_settings.revision+1,updated_at=excluded.updated_at;
END;
CREATE TRIGGER site_settings_account_center_update AFTER UPDATE ON account_center_setting BEGIN
INSERT INTO site_settings (key,value,revision,updated_at) SELECT 'account_center',json_object('profileEditingEnabled', json(CASE WHEN profile_editing_enabled THEN 'true' ELSE 'false' END), 'passwordChangeEnabled', json(CASE WHEN password_change_enabled THEN 'true' ELSE 'false' END), 'connectedAccountsEnabled', json(CASE WHEN connected_accounts_enabled THEN 'true' ELSE 'false' END), 'sessionsViewEnabled', json(CASE WHEN sessions_view_enabled THEN 'true' ELSE 'false' END), 'dangerZoneEnabled', json(CASE WHEN danger_zone_enabled THEN 'true' ELSE 'false' END), 'displayNameEditable', json(CASE WHEN COALESCE(json_extract(COALESCE(metadata, '{}'), '$.fieldPermissions.displayNameEditable'), 1) THEN 'true' ELSE 'false' END), 'usernameEditable', json(CASE WHEN COALESCE(json_extract(COALESCE(metadata, '{}'), '$.fieldPermissions.usernameEditable'), 1) THEN 'true' ELSE 'false' END), 'avatarEditable', json(CASE WHEN COALESCE(json_extract(COALESCE(metadata, '{}'), '$.fieldPermissions.avatarEditable'), 1) THEN 'true' ELSE 'false' END), 'emailChangeEnabled', json(CASE WHEN COALESCE(json_extract(COALESCE(metadata, '{}'), '$.fieldPermissions.emailChangeEnabled'), 1) THEN 'true' ELSE 'false' END), 'metadata', json(COALESCE(metadata, '{}'))),1,updated_at FROM account_center_setting WHERE id = NEW.id ON CONFLICT(key) DO UPDATE SET value=excluded.value,revision=site_settings.revision+1,updated_at=excluded.updated_at;
END;
INSERT INTO site_settings (key,value,revision,updated_at) SELECT 'branding',json_object('logoUrl', logo_url, 'faviconUrl', favicon_url, 'logoAssetId', logo_asset_id, 'faviconAssetId', favicon_asset_id, 'primaryColor', primary_color, 'backgroundColor', background_color, 'customCss', custom_css),1,updated_at FROM branding_setting;
CREATE TRIGGER site_settings_branding_insert AFTER INSERT ON branding_setting BEGIN
INSERT INTO site_settings (key,value,revision,updated_at) SELECT 'branding',json_object('logoUrl', logo_url, 'faviconUrl', favicon_url, 'logoAssetId', logo_asset_id, 'faviconAssetId', favicon_asset_id, 'primaryColor', primary_color, 'backgroundColor', background_color, 'customCss', custom_css),1,updated_at FROM branding_setting WHERE id = NEW.id ON CONFLICT(key) DO UPDATE SET value=excluded.value,revision=site_settings.revision+1,updated_at=excluded.updated_at;
END;
CREATE TRIGGER site_settings_branding_update AFTER UPDATE ON branding_setting BEGIN
INSERT INTO site_settings (key,value,revision,updated_at) SELECT 'branding',json_object('logoUrl', logo_url, 'faviconUrl', favicon_url, 'logoAssetId', logo_asset_id, 'faviconAssetId', favicon_asset_id, 'primaryColor', primary_color, 'backgroundColor', background_color, 'customCss', custom_css),1,updated_at FROM branding_setting WHERE id = NEW.id ON CONFLICT(key) DO UPDATE SET value=excluded.value,revision=site_settings.revision+1,updated_at=excluded.updated_at;
END;
INSERT INTO site_settings (key,value,revision,updated_at) SELECT 'email',json_object('provider', provider, 'enabled', json(CASE WHEN enabled THEN 'true' ELSE 'false' END), 'fromEmail', from_email, 'fromName', from_name, 'replyToEmail', reply_to_email, 'defaultLocale', default_locale, 'metadata', json(COALESCE(metadata, '{}'))),1,updated_at FROM email_service_config;
CREATE TRIGGER site_settings_email_insert AFTER INSERT ON email_service_config BEGIN
INSERT INTO site_settings (key,value,revision,updated_at) SELECT 'email',json_object('provider', provider, 'enabled', json(CASE WHEN enabled THEN 'true' ELSE 'false' END), 'fromEmail', from_email, 'fromName', from_name, 'replyToEmail', reply_to_email, 'defaultLocale', default_locale, 'metadata', json(COALESCE(metadata, '{}'))),1,updated_at FROM email_service_config WHERE id = NEW.id ON CONFLICT(key) DO UPDATE SET value=excluded.value,revision=site_settings.revision+1,updated_at=excluded.updated_at;
END;
CREATE TRIGGER site_settings_email_update AFTER UPDATE ON email_service_config BEGIN
INSERT INTO site_settings (key,value,revision,updated_at) SELECT 'email',json_object('provider', provider, 'enabled', json(CASE WHEN enabled THEN 'true' ELSE 'false' END), 'fromEmail', from_email, 'fromName', from_name, 'replyToEmail', reply_to_email, 'defaultLocale', default_locale, 'metadata', json(COALESCE(metadata, '{}'))),1,updated_at FROM email_service_config WHERE id = NEW.id ON CONFLICT(key) DO UPDATE SET value=excluded.value,revision=site_settings.revision+1,updated_at=excluded.updated_at;
END;
