import type { Deps } from '@server/usecases/deps'
import type { SecurityPolicy } from '@shared/api/security'
import { vi } from 'vitest'

export function testSecurityPolicy(): SecurityPolicy {
  return {
    mfa: { mode: 'optional', emailOtpEnabled: false, authenticatorAppEnabled: true },
    passkeys: {
      enabled: true,
      rpId: 'auth.example.com',
      rpName: 'Realmroot',
      origins: ['https://auth.example.com'],
    },
    sessions: {
      expiresInSeconds: 60 * 60 * 24 * 7,
      updateAgeSeconds: 60 * 60 * 24,
      freshAgeSeconds: 60 * 60 * 24,
      cookieCacheSeconds: 60 * 5,
    },
    password: {
      minLength: 8,
      requiredCharacterTypes: 1,
      customWords: [],
      rejectUserInfo: false,
      rejectSequential: false,
      rejectCustomWords: false,
    },
    captcha: { enabled: false, provider: 'turnstile', siteKey: '', projectId: null, secretKey: '' },
    blocklist: { blockSubaddressing: false, entries: [] },
  } as SecurityPolicy
}

function emptyPage() {
  return { items: [], total: 0, limit: 20, offset: 0 }
}

/**
 * A permissive fake Deps for route/app tests. Every port is a vi.fn with a
 * benign default; tests override only the slices they exercise via `overrides`.
 */
export function createTestDeps(overrides: Partial<Record<keyof Deps, unknown>> = {}): Deps {
  const policy = testSecurityPolicy()
  const base = {
    agents: {
      listHosts: vi.fn().mockResolvedValue(emptyPage()),
      listAgents: vi.fn().mockResolvedValue(emptyPage()),
      listCapabilityGrants: vi.fn().mockResolvedValue(emptyPage()),
      listApprovalRequests: vi.fn().mockResolvedValue(emptyPage()),
      findApprovalRequest: vi.fn().mockResolvedValue(null),
      createApprovalRequest: vi.fn().mockImplementation(async (record) => record),
      listAgentsForUser: vi.fn().mockResolvedValue(emptyPage()),
      listHostsForAgents: vi.fn().mockResolvedValue([]),
      listCapabilityGrantsForUser: vi.fn().mockResolvedValue([]),
      listCapabilityGrantsForAgent: vi.fn().mockResolvedValue([]),
      decideApproval: vi.fn(),
      revokeAgentForUser: vi.fn().mockResolvedValue(undefined),
      revokeCapabilityGrantForUser: vi.fn().mockResolvedValue(undefined),
      revokeAgent: vi.fn().mockResolvedValue(undefined),
      revokeHost: vi.fn().mockResolvedValue(undefined),
      revokeCapabilityGrant: vi.fn().mockResolvedValue(undefined),
    },
    agentAudit: {
      append: vi.fn(),
      list: vi.fn().mockResolvedValue({ items: [], total: 0 }),
    },
    agentIdentities: {
      listPersonal: vi.fn().mockResolvedValue([]),
      listOrganization: vi.fn().mockResolvedValue([]),
      listOwned: vi.fn().mockResolvedValue(emptyPage()),
      listAll: vi.fn().mockResolvedValue({ items: [], total: 0 }),
      findIdentity: vi.fn().mockResolvedValue(null),
      findByIssuerSubject: vi.fn().mockResolvedValue(null),
      findIntent: vi.fn().mockResolvedValue(null),
      findIntentByIdempotencyKey: vi.fn().mockResolvedValue(null),
      findProtocolAgent: vi.fn().mockResolvedValue(null),
      findBindingByProtocolAgent: vi.fn().mockResolvedValue(null),
      findActiveByProtocolAgent: vi.fn().mockResolvedValue(null),
      createIdentity: vi.fn(),
      createIntent: vi.fn(),
      createIntentIdempotently: vi.fn(),
      approveIntent: vi.fn(),
      revokeBinding: vi.fn().mockResolvedValue(false),
      recoverIdentity: vi.fn().mockResolvedValue(false),
      retireIdentity: vi.fn().mockResolvedValue(false),
    },
    agentTokens: {
      consumeAgentAuthJti: vi.fn().mockResolvedValue(true),
      consumeDpopJti: vi.fn().mockResolvedValue(true),
    },
    applications: {
      create: vi.fn(),
      list: vi.fn().mockResolvedValue({
        items: [],
        pagination: { limit: 100, offset: 0, total: 0, hasMore: false, nextOffset: null },
      }),
      findById: vi.fn().mockResolvedValue(null),
      findByClientId: vi.fn().mockResolvedValue(null),
      update: vi.fn(),
      delete: vi.fn(),
      listSecrets: vi.fn().mockResolvedValue({
        items: [],
        pagination: { limit: 20, offset: 0, total: 0, hasMore: false, nextOffset: null },
      }),
      rotateSecret: vi.fn(),
      listAuthorizations: vi.fn().mockResolvedValue({
        items: [],
        pagination: { limit: 50, offset: 0, total: 0, hasMore: false, nextOffset: null },
      }),
      revokeAuthorization: vi.fn().mockResolvedValue(true),
      findConsent: vi.fn().mockResolvedValue(null),
      revokeConsent: vi.fn().mockResolvedValue(true),
      createConsent: vi.fn(),
    },
    assets: {
      createAsset: vi.fn(),
      findAsset: vi.fn().mockResolvedValue(null),
      updateUserAvatar: vi.fn(),
      updateApplicationLogo: vi.fn(),
      updateOrganizationLogo: vi.fn(),
      updateBrandingAsset: vi.fn(),
    },
    assetStorage: { put: vi.fn(), get: vi.fn().mockResolvedValue(null) },
    authorization: {
      listEnabledResources: vi.fn().mockResolvedValue([]),
      listUserMemberships: vi.fn().mockResolvedValue([]),
      listMemberUserIds: vi.fn().mockResolvedValue([]),
      listOrganizationRoles: vi.fn().mockResolvedValue([]),
      listOrganizationRoleScopes: vi.fn().mockResolvedValue(new Map()),
      findMemberByOrganizationUser: vi.fn().mockResolvedValue(null),
      findOrganization: vi.fn().mockResolvedValue(null),
      findResource: vi.fn().mockResolvedValue(null),
      hasPendingInvitation: vi.fn().mockResolvedValue(false),
    },
    configz: {
      getSettings: vi.fn().mockResolvedValue(null),
      getBranding: vi.fn().mockResolvedValue(null),
      getAccountCenterSettings: vi.fn().mockResolvedValue(null),
      getOrganizationCreationPolicy: vi.fn().mockResolvedValue({ mode: 'admins_only', approvedUserIds: [] }),
      getDeveloperConsoleAccessPolicy: vi.fn().mockResolvedValue({
        mode: 'realm_operators',
        eligibleAccessLevels: ['owner', 'admin', 'developer'],
        selectedOrganizationIds: [],
      }),
      getEmailSettings: vi.fn().mockResolvedValue(null),
      listEnabledIdentityProviders: vi.fn().mockResolvedValue([]),
      updateSettings: vi.fn(),
      updateBranding: vi.fn(),
      updateAccountCenterSettings: vi.fn(),
      updateOrganizationCreationPolicy: vi.fn(),
      updateDeveloperConsoleAccessPolicy: vi.fn(),
      updateEmailSettings: vi.fn(),
    },
    connectors: {
      list: vi.fn().mockResolvedValue({ items: [], total: 0 }),
      listEnabled: vi.fn().mockResolvedValue([]),
      findById: vi.fn().mockResolvedValue(null),
      findByProviderId: vi.fn().mockResolvedValue(null),
      countResourceReferences: vi.fn().mockResolvedValue(0),
      create: vi.fn(),
      update: vi.fn(),
      delete: vi.fn(),
    },
    externalResources: {
      createConnection: vi.fn().mockImplementation(async (input) => input),
      findConnectionByOwnerResource: vi.fn().mockResolvedValue(null),
      replaceConnectionAuthorization: vi.fn().mockResolvedValue(null),
      listConnectionsByUser: vi.fn().mockResolvedValue([]),
      listConnectionsByOrganizations: vi.fn().mockResolvedValue([]),
      findConnection: vi.fn().mockResolvedValue(null),
      updateConnectionTokens: vi.fn().mockResolvedValue(null),
      revokeConnection: vi.fn().mockResolvedValue(false),
      createConnectionIntent: vi.fn().mockImplementation(async (input) => input),
      consumeConnectionIntent: vi.fn().mockResolvedValue(null),
      createAgentConnectionRequest: vi.fn().mockImplementation(async (input) => input),
      findAgentConnectionRequest: vi.fn().mockResolvedValue(null),
      findAgentConnectionRequestByApprovalTokenHash: vi.fn().mockResolvedValue(null),
      createAccessRequest: vi.fn().mockImplementation(async (input) => input),
      findAccessRequest: vi.fn().mockResolvedValue(null),
      findAccessRequestByGrant: vi.fn().mockResolvedValue(null),
      findAccessRequestByApprovalTokenHash: vi.fn().mockResolvedValue(null),
      listAccessRequests: vi.fn().mockResolvedValue(emptyPage()),
      listPendingAccessRequestsByAgent: vi.fn().mockResolvedValue([]),
      listPendingAccessRequests: vi.fn().mockResolvedValue([]),
      decideAccessRequest: vi.fn().mockResolvedValue(null),
      consumeAccessRequest: vi.fn().mockResolvedValue(false),
      listPendingAccessRequestsByConnections: vi.fn().mockResolvedValue([]),
      createGrant: vi.fn().mockImplementation(async (input) => input),
      findGrant: vi.fn().mockResolvedValue(null),
      listActiveGrantsByAgent: vi.fn().mockResolvedValue([]),
      listGrants: vi.fn().mockResolvedValue(emptyPage()),
      summarizeAgentAccess: vi.fn().mockResolvedValue(new Map()),
      listActiveGrantsByConnection: vi.fn().mockResolvedValue([]),
      revokeGrant: vi.fn().mockResolvedValue(false),
      consumeGrant: vi.fn().mockResolvedValue(false),
      createTokenLease: vi.fn().mockImplementation(async (input) => input),
      listActiveTokenLeasesByGrant: vi.fn().mockResolvedValue([]),
      listActiveTokenLeasesByBinding: vi.fn().mockResolvedValue([]),
      revokeTokenLease: vi.fn().mockResolvedValue(false),
    },
    externalHttp: { fetch: vi.fn() },
    onboarding: {
      hasUsers: vi.fn().mockResolvedValue(true),
      createBootstrapAdmin: vi.fn(),
    },
    security: {
      getPolicy: vi.fn().mockResolvedValue(policy),
      updatePolicy: vi.fn().mockResolvedValue(policy),
      getSecurityState: vi.fn().mockResolvedValue({
        userId: 'user-1',
        mfa: { enabled: true, factors: [{ id: 'factor-1', type: 'totp', verified: true }] },
        passkeys: { enabled: true, count: 1 },
        policy,
      }),
      listPasskeys: vi.fn().mockResolvedValue(emptyPage()),
      deletePasskey: vi.fn(),
      getSessionToken: vi.fn().mockResolvedValue('session-token-1'),
    },
    secrets: {
      isSealed: vi.fn((value: string) => value.startsWith('sealed:')),
      seal: vi.fn(async (value: string) => `sealed:${value}`),
      open: vi.fn(async (value: string) => value.replace(/^sealed:/, '')),
    },
    tokenExchange: {
      findClient: vi.fn().mockResolvedValue(null),
      findFederatedCredentials: vi.fn().mockResolvedValue([]),
      findFederatedCredentialForClient: vi.fn().mockResolvedValue(null),
      listFederatedCredentials: vi.fn().mockResolvedValue([]),
      getFederatedCredential: vi.fn().mockResolvedValue(null),
      createFederatedCredential: vi.fn(),
      updateFederatedCredential: vi.fn().mockResolvedValue(null),
      deleteFederatedCredential: vi.fn().mockResolvedValue(false),
      storeAccessToken: vi.fn(),
      findAccessTokenByHash: vi.fn().mockResolvedValue(null),
      storeRefreshToken: vi.fn().mockResolvedValue(true),
      findRefreshTokenByHash: vi.fn().mockResolvedValue(null),
      consumeRefreshToken: vi.fn().mockResolvedValue(false),
      revokeRefreshTokenFamily: vi.fn(),
    },
    users: {
      getUser: vi.fn().mockImplementation((id: string) =>
        Promise.resolve({
          id,
          email: `${id}@example.com`,
          emailVerified: true,
          role: 'user',
        }),
      ),
      listManagedUsers: vi.fn().mockResolvedValue(emptyPage()),
      createManagedUser: vi.fn(),
      updateManagedUser: vi.fn(),
      deleteManagedUser: vi.fn(),
      updateProfile: vi.fn(),
      assertAccountAvatarReference: vi.fn(),
      assertAdminAvatarReference: vi.fn(),
      listLinkedAccounts: vi.fn().mockResolvedValue(emptyPage()),
      listConsentedApplications: vi.fn().mockResolvedValue(emptyPage()),
      listSessions: vi.fn().mockResolvedValue(emptyPage()),
      getSessionToken: vi.fn().mockResolvedValue('session-token-1'),
    },
    wallets: {
      findWalletAddress: vi.fn().mockResolvedValue(null),
      findAnyWalletAddress: vi.fn().mockResolvedValue(null),
      getSiweNonce: vi.fn().mockResolvedValue(null),
      deleteSiweNonce: vi.fn(),
      linkWalletAddress: vi.fn(),
      unlinkWalletAddress: vi.fn(),
    },
    webhooks: {
      listEndpoints: vi.fn().mockResolvedValue({ items: [], total: 0 }),
      listSubscribedEndpoints: vi.fn().mockResolvedValue([]),
      findEndpoint: vi.fn().mockResolvedValue(null),
      createEndpoint: vi.fn(),
      updateEndpoint: vi.fn(),
      deleteEndpoint: vi.fn(),
      listRequests: vi.fn().mockResolvedValue({ items: [], total: 0 }),
      findRequest: vi.fn().mockResolvedValue(null),
      createRequest: vi.fn(),
      updateRequest: vi.fn(),
      listAttempts: vi.fn().mockResolvedValue(emptyPage()),
      findAttempt: vi.fn().mockResolvedValue(null),
      findAttemptByIdempotencyKey: vi.fn().mockResolvedValue(null),
      reserveAttempt: vi.fn(),
      updateAttempt: vi.fn(),
    },
    email: { send: vi.fn() },
    jwks: { fetchKeys: vi.fn() },
  }

  return Object.fromEntries(
    Object.entries(base).map(([key, value]) => [
      key,
      { ...value, ...((overrides[key as keyof Deps] as object | undefined) ?? {}) },
    ]),
  ) as unknown as Deps
}
